# Maintainer: Vladislav 'fsLeg' Borisov <fsleg at t-rg dot ws>

PRGNAM="amnezia-client"
VERSION="5.0.1.5"
BUILD="${BUILD:-1}"
DESCRIPTION="Amnezia VPN client for desktop"
HOMEPAGE="https://amnezia.org"
DOWNLOAD="https://github.com/amnezia-vpn/amnezia-client/archive/${VERSION}/${PRGNAM}-${VERSION}.tar.gz"
SHA256SUM="478a3a983c8e20ba2317b5df69db4a202afcc72629890318025cad7c61fb0c99"

unpack () {
  if [ ! "$SLACKVER" = "current" ]; then
    echo "This SlackBuild only works on -current."
    exit 1
  fi

  $UNTAR $CWD/$PRGNAM-$VERSION.tar.gz

  # get branches with necessary files
  sed -i '/SortFilterProxyModel.git/a\\tbranch = qt-6
          /special-handshake/d' \
          $PRGNAM-$VERSION/.gitmodules
  get_submodules $PRGNAM-$VERSION

  # Conan. I'm not dealing with it
  python3 -m venv $PRGNAM-$VERSION/conan
  source $PRGNAM-$VERSION/conan/bin/activate
  pip install conan
  export CONAN_HOME=$TMP/.conan2
  unset GOROOT

  # Export AGW public key and S3 endpoint for VPN from Amnezia to work
  export PROD_AGW_PUBLIC_KEY="-----BEGIN PUBLIC KEY-----\nMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAj5mxl/4DL3Sk89ntxs5G\nX3JawGQWIoq6rvNkOzNGuNgedNS2+pi6hZl3Izl1Io9om4KiUlMT6mgLO1hTr9q+\ns7CYhlvroFA7ErucF+9L+7FCt0Igi0kIK/R2/vxd/2HaUrorn/aSvvutkYwbfxqW\nSwtzE+RuBeDWGvEt937OW0oqYONPYv9E4T56Dz/EZ6v2t8ejAnKLbGD/GocMmipK\n7etFSiSMAB2RmaztqTq4NleBepfO80XpYlW9pCSXuHcE8wxHczkzxsbyMAMsG/K3\nvUQY6qPtohqqzSSBwa/8u2ptNHBeor7l7DdYXeR/Nqcc4z92VUkZ5lOVR4evkS5V\n/wQqp5tnOJEj3NjUhEhXFoNEapbZd1bh6iQoUk7jC1TdvKJ/nPKGZAsHRpr0rNKz\nfx/N/Oo6lr2yh/+ps6VxTkbPmB6E85WOO3UvjImZUY0XQdBjWle/4iJLdEC77Nr0\njXhdgeypucy6jkB6iBHMeVMlrNMEV7UxoBR/cCNx55zu/8sml5ByiDvCDT7sRomN\nNgVt5S/FaVjYuzFUifJ12ToChXFgESKFmuso7WluEaWvMIGREdrMrKQKHfYLOzWF\n2B5ZJDqw4o03fU4J/6rw61M1b+rjVpXMjPnzc2A+RgcjTvXv955gfZkwe4lt5wk/\n3j8zMVo3+zLrMTAaEeIUM0UCAwEAAQ==\n-----END PUBLIC KEY-----"
  export PROD_S3_ENDPOINT="https://s3.eu-north-1.amazonaws.com/amnezia/endpoints.json, https://storage.googleapis.com/lambda-list/endpoints.json"
}

build () {
  # BFD can't properly link, MOLD makes the binaries segfault, LLD works
  # but requires the rest of LLVM
  CC="clang" \
  CXX="clang++" \
  LDFLAGS+="-fuse-ld=lld" \
  QT_ROOT_PATH=$QT6DIR \
    ./deploy/build.sh

  install -Dm755 -t $PKG/$_PREFIX/lib$LIBDIRSUFFIX/$PRGNAM \
    deploy/build/client/{AmneziaVPN,update-resolv-conf.sh}
  install -d $PKG/$_PREFIX/bin $PKG/install
  ln -sf ../lib$LIBDIRSUFFIX/$PRGNAM/AmneziaVPN $PKG/$_PREFIX/bin/
  install -Dm755 -t $PKG/$_PREFIX/lib$LIBDIRSUFFIX/$PRGNAM \
    deploy/build/service/server/{AmneziaVPN-service,amneziawg-go,geo*.dat,openvpn,tun2socks}
  patchelf --remove-rpath $PKG/$_PREFIX/lib$LIBDIRSUFFIX/$PRGNAM/{AmneziaVPN*,openvpn}
  install -Dm755 $CWD/rc.amnezia $PKG/$SYSCONFDIR/rc.d/rc.amnezia.new
  sed -i "s|@PREFIX@|$_PREFIX|g
          s|@LIBDIRSUFFIX@|$LIBDIRSUFFIX|g" \
    $PKG/$SYSCONFDIR/rc.d/rc.amnezia.new
  install -Dm644 -t $PKG/$_PREFIX/share/applications \
    deploy/data/linux/AmneziaVPN.desktop
  sed -i 's|/usr/share/pixmaps/AmneziaVPN\.png|AmneziaVPN|
          /Version=/d' \
    $PKG/$_PREFIX/share/applications/AmneziaVPN.desktop
  for geometry in 16x16 24x24 32x32 48x48 64x64 96x96 128x128 256x256 512x512; do
    install -d $PKG/$_PREFIX/share/icons/hicolor/$geometry/apps
    magick deploy/data/linux/AmneziaVPN.png -resize $geometry \
           $PKG/$_PREFIX/share/icons/hicolor/$geometry/apps/AmneziaVPN.png
  done
  sed "s|@SYSCONFDIR@|${SYSCONFDIR#/}|g" $CWD/doinst.sh > $PKG/install/doinst.sh
  install -Dm644 -t $PKG/$_PREFIX/doc/$PRGNAM-$VERSION *LICENSE* README*.md
}
