# Maintainer: Vladislav 'fsLeg' Borisov <fsleg at t-rg dot ws>

PRGNAM="amnezia-client"
VERSION="4.8.15.4"
BUILD="${BUILD:-1}"
DESCRIPTION="Amnezia VPN client for desktop"
HOMEPAGE="https://amnezia.org"
DOWNLOAD="https://github.com/amnezia-vpn/amnezia-client/archive/${VERSION}/${PRGNAM}-${VERSION}.tar.gz"
SHA256SUM="02760cb859106999a345581509af51c192ebd26bb91b98b1b57a358384c37a3d"

unpack () {
  if [ ! "$SLACKVER" = "current" ]; then
    echo "This SlackBuild only works on -current."
    exit 1
  fi

  tar xvf $CWD/$PRGNAM-$VERSION.tar.gz

  # get branches with necessary files
  sed -i '/SortFilterProxyModel.git/a\\tbranch = qt-6
          /special-handshake/d' \
          $PRGNAM-$VERSION/.gitmodules
  get_submodules $PRGNAM-$VERSION

  # apply patches from ALT Linux
  # https://packages.altlinux.org/en/sisyphus/srpms/amnezia-vpn/specfiles/
  patch -p1 -d $PRGNAM-$VERSION < $CWD/amnezia-vpn-tun2-sudo.patch
  # Fix utilites exec path
  sed -e 's|return Utils::executable("../../client/bin/openvpn", true);|return Utils::usrExecutable("'$_PREFIX/lib$LIBDIRSUFFIX/$PRGNAM'/openvpn");|' \
      -e 's|return Utils::executable("../../client/bin/tun2socks", true);|return Utils::usrExecutable("'$_PREFIX/lib$LIBDIRSUFFIX/$PRGNAM'/tun2socks");|' \
      -i $PRGNAM-$VERSION/client/utilities.cpp
  # Fix WireGuard GO exec path
  sed -e 's|m_tunnel.start(appPath.filePath("../../client/bin/wireguard-go"), wgArgs);|m_tunnel.start("'$_PREFIX/lib$LIBDIRSUFFIX/$PRGNAM'/wireguard-go", wgArgs);|' \
      -i $PRGNAM-$VERSION/client/platforms/linux/daemon/wireguardutilslinux.cpp
  # Fix update resolv conf path
  sed -e 's|.arg(qApp->applicationDirPath());|.arg("'$_PREFIX/lib$LIBDIRSUFFIX/$PRGNAM'");|' \
      -i $PRGNAM-$VERSION/client/configurators/openvpn_configurator.cpp
  # Use system libs instead of 3rd-party prebuild ones
  sed -e 's|set(ZLIB_LIB_PATH "${LIBSSH_ROOT_DIR}/linux/x86_64/libz.a")|set(ZLIB_LIB_PATH "/usr/lib'$LIBDIRSUFFIX'/libz.so")|' \
      -e 's|set(LIBSSH_LIB_PATH "${LIBSSH_ROOT_DIR}/linux/x86_64/libssh.a")|set(LIBSSH_LIB_PATH "/usr/lib'$LIBDIRSUFFIX'/libssh.so")|' \
      -e 's|set(OPENSSL_INCLUDE_DIR "${OPENSSL_ROOT_DIR}/linux/include")|set(OPENSSL_INCLUDE_DIR "/usr/include")|' \
      -e 's|set(OPENSSL_LIB_SSL_PATH "${OPENSSL_ROOT_DIR}/linux/x86_64/libssl.a")|set(OPENSSL_LIB_SSL_PATH "/usr/lib'$LIBDIRSUFFIX'/libssl.so")|' \
      -e 's|set(OPENSSL_LIB_CRYPTO_PATH "${OPENSSL_ROOT_DIR}/linux/x86_64/libcrypto.a")|set(OPENSSL_LIB_CRYPTO_PATH "/usr/lib'$LIBDIRSUFFIX'/libcrypto.so")|' \
      -e 's|set(OPENSSL_USE_STATIC_LIBS TRUE)|set(OPENSSL_USE_STATIC_LIBS FALSE)|' \
      -i $PRGNAM-$VERSION/client/cmake/3rdparty.cmake
  sed -e 's|set(OPENSSL_INCLUDE_DIR "${OPENSSL_ROOT_DIR}/linux/include")|set(OPENSSL_INCLUDE_DIR "/usr/include")|' \
      -e 's|set(OPENSSL_LIB_CRYPTO_PATH "${OPENSSL_ROOT_DIR}/linux/x86_64/libcrypto.a")|set(OPENSSL_LIB_CRYPTO_PATH "/usr/lib'$LIBDIRSUFFIX'/libcrypto.so")|' \
      -e 's|set(OPENSSL_USE_STATIC_LIBS TRUE)|set(OPENSSL_USE_STATIC_LIBS FALSE)|' \
      -i $PRGNAM-$VERSION/service/server/CMakeLists.txt
  # Export AGW public key and S3 endpoint for VPN from Amnezia to work
  export PROD_AGW_PUBLIC_KEY="-----BEGIN PUBLIC KEY-----\nMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAj5mxl/4DL3Sk89ntxs5G\nX3JawGQWIoq6rvNkOzNGuNgedNS2+pi6hZl3Izl1Io9om4KiUlMT6mgLO1hTr9q+\ns7CYhlvroFA7ErucF+9L+7FCt0Igi0kIK/R2/vxd/2HaUrorn/aSvvutkYwbfxqW\nSwtzE+RuBeDWGvEt937OW0oqYONPYv9E4T56Dz/EZ6v2t8ejAnKLbGD/GocMmipK\n7etFSiSMAB2RmaztqTq4NleBepfO80XpYlW9pCSXuHcE8wxHczkzxsbyMAMsG/K3\nvUQY6qPtohqqzSSBwa/8u2ptNHBeor7l7DdYXeR/Nqcc4z92VUkZ5lOVR4evkS5V\n/wQqp5tnOJEj3NjUhEhXFoNEapbZd1bh6iQoUk7jC1TdvKJ/nPKGZAsHRpr0rNKz\nfx/N/Oo6lr2yh/+ps6VxTkbPmB6E85WOO3UvjImZUY0XQdBjWle/4iJLdEC77Nr0\njXhdgeypucy6jkB6iBHMeVMlrNMEV7UxoBR/cCNx55zu/8sml5ByiDvCDT7sRomN\nNgVt5S/FaVjYuzFUifJ12ToChXFgESKFmuso7WluEaWvMIGREdrMrKQKHfYLOzWF\n2B5ZJDqw4o03fU4J/6rw61M1b+rjVpXMjPnzc2A+RgcjTvXv955gfZkwe4lt5wk/\n3j8zMVo3+zLrMTAaEeIUM0UCAwEAAQ==\n-----END PUBLIC KEY-----"
  export PROD_S3_ENDPOINT="https://s3.eu-north-1.amazonaws.com/amnezia/endpoints.json, https://storage.googleapis.com/lambda-list/endpoints.json"
}

build () {
  # mold makes the binaries segfault
  LDFLAGS+=" -fuse-ld=bfd" \
    qt-cmake -B build
  cmake --build build --config release

  install -Dm755 -t $PKG/$_PREFIX/lib$LIBDIRSUFFIX/$PRGNAM \
                    deploy/data/deploy-prebuilt/linux/client/bin/{ck-client,openvpn,ss-local,tun2socks,wireguard-go} \
                    deploy/data/linux/client/bin/update-resolv-conf.sh \
                    build/client/AmneziaVPN
  install -d $PKG/$_PREFIX/bin \
             $PKG/install
  ln -sf ../lib$LIBDIRSUFFIX/$PRGNAM/AmneziaVPN $PKG/$_PREFIX/bin/
  install -Dm755 -t $PKG/$_PREFIX/lib$LIBDIRSUFFIX/$PRGNAM \
                    build/service/server/AmneziaVPN-service
  install -Dm755 $CWD/rc.amnezia $PKG/$SYSCONFDIR/rc.d/rc.amnezia.new
  sed -i "s|@PREFIX@|$_PREFIX|g; s|@LIBDIRSUFFIX@|$LIBDIRSUFFIX|g" \
         $PKG/$SYSCONFDIR/rc.d/rc.amnezia.new
  install -Dm644 -t $PKG/$_PREFIX/share/applications \
                    AppDir/AmneziaVPN.desktop
  sed -i 's|/usr/share/pixmaps/AmneziaVPN\.png|AmneziaVPN|; /Version=/d' \
         $PKG/$_PREFIX/share/applications/AmneziaVPN.desktop
  for geometry in 16x16 24x24 32x32 48x48 64x64 96x96 128x128 256x256 512x512; do
    install -d $PKG/$_PREFIX/share/icons/hicolor/$geometry/apps
    magick deploy/data/linux/AmneziaVPN.png -resize $geometry \
           $PKG/$_PREFIX/share/icons/hicolor/$geometry/apps/AmneziaVPN.png
  done
  sed "s|@SYSCONFDIR@|${SYSCONFDIR#/}|g" $CWD/doinst.sh > $PKG/install/doinst.sh
  install -Dm644 -t $PKG/$_PREFIX/doc/$PRGNAM-$VERSION LICENSE README.md
}
