# Maintainer: Vladislav 'fsLeg' Borisov <fsleg at t-rg dot ws>

PRGNAM="hugo"
VERSION="0.155.3"
BUILD="${BUILD:-1}"
DESCRIPTION="static HTML and CSS website generator written in Go"
HOMEPAGE="https://gohugo.io/"
DOWNLOAD="https://github.com/gohugoio/hugo/archive/v${VERSION}/${PRGNAM}-${VERSION}.tar.gz"
SHA256SUM="2e37575fd0627f6f4696027cd90c99d48376b403f71d58945987ad967890b283"
BUILD_REQUIRES="google-go-lang"
OPTIONAL="dart-sass"

unpack () {
  tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
}

build () {
  if [ "${EXTENDED:-yes}" = "yes" ] || [ "${DEPLOY:-yes}" = "yes" ]; then
    TAGS="-tags "
    if [ "${EXTENDED:-yes}" = "yes" ]; then
      TAGS+="extended,"
      CFLAGS_SYS="$(pkg-config --cflags libsass) -DUSE_LIBSASS_SRC \
                  $(pkg-config --cflags libwebp) -DLIBWEBP_NO_SRC"
      LDFLAGS_SYS="$(pkg-config --libs libsass) \
                   $(pkg-config --libs libwebp)"
    fi
    if [ "${DEPLOY:-yes}" = "yes" ]; then
      TAGS+="withdeploy"
    fi
  fi

  CGO_CFLAGS="$CGO_CFLAGS $CFLAGS_SYS" \
  CGO_CXXFLAGS="$CGO_CFLAGS" \
  CGO_CPPFLAGS="$CGO_CFLAGS" \
  CGO_LDFLAGS="$LDFLAGS_SYS" \
  go build -v \
     $TAGS \
     -buildvcs=false \
     -buildmode=pie \
     -mod=readonly \
     -modcacherw \
     -ldflags "-compressdwarf=false \
               -linkmode external \
               -extldflags '${LDFLAGS}'"

  install -Dm755 -t $PKG/$_PREFIX/bin hugo
  install -d $PKG/$_PREFIX/share/bash-completion/completions \
             $PKG/$_PREFIX/share/fish/vendor_completions.d \
             $PKG/$_PREFIX/share/zsh/site-functions
  ./hugo completion bash > $PKG/$_PREFIX/share/bash-completion/completions/$PRGNAM
  ./hugo completion fish > $PKG/$_PREFIX/share/fish/vendor_completions.d/$PRGNAM.fish
  ./hugo completion zsh > $PKG/$_PREFIX/share/zsh/site-functions/_$PRGNAM
  ./hugo gen doc --dir $PKG/$_PREFIX/doc/$PRGNAM-$VERSION
  install -Dm644 -t $PKG/$_PREFIX/doc/$PRGNAM-$VERSION \
    CONTRIBUTING.md LICENSE README.md SECURITY.md
}

