# Maintainer: Vladislav 'fsLeg' Borisov <fsleg at t-rg dot ws>

PRGNAM="PrismLauncher"
VERSION="11.0.3"
BUILD="${BUILD:-1}"
DESCRIPTION="Open Source Minecraft launcher"
HOMEPAGE="https://prismlauncher.org/"
DOWNLOAD="https://github.com/${PRGNAM}/${PRGNAM}/archive/${VERSION}/${PRGNAM}-${VERSION}.tar.gz"
SHA256SUM="c66f1267c8d4f3be6838bf8c02ae30eb149ba8d92c75455406db42e1b0aff1c5"
REQUIRES="qt6 gamemode tomlplusplus cmark"
BUILD_REQUIRES="cmake-opt jdk|openjdk8|zulu-openjdk8|jdk11|OpenJDK11|zulu-openjdk11|OpenJDK17|zulu-openjdk17|jdk19|OpenJDK21|zulu-openjdk21|jdk23|zulu-openjdk25"
OPTIONAL="scdoc glfw3 flite orca"
CONFLICTS="PrismLauncher-Unlocked"
PKGVER="${VERSION//-/.}" # fix package name for pre-releases

unpack () {
  $UNTAR $CWD/$PRGNAM-$VERSION.tar.gz

  # get dependencies for git sources
  if [ -z "$(ls -A $PRGNAM-$VERSION/libraries/libnbtplusplus)" ]; then
    get_submodules $PRGNAM-$VERSION
  fi

  # fix building with newer Java
  if [ "$(java -version 2>&1 | awk -F'[ ".]' '/version/ {print $4}')" -ge 21 ]; then
    sed -i 's/-target 7 -source 7/--release 8 -Xlint:-options/' $PRGNAM-$VERSION/libraries/{javacheck,launcher}/CMakeLists.txt
  fi

  # fix man path, do not set RPATH
  sed -i 's/KDE_INSTALL_MANDIR/MAN_INSTALL_DIR/; /RPATH/d' $PRGNAM-$VERSION/CMakeLists.txt
}

build () {
  # the linker chokes if there's no "-ldl" ldflag; -current doesn't need this
  cmake --preset linux \
        -Wno-dev \
        -DENABLE_LTO="ON" \
        -DCMAKE_C_FLAGS="$SLKCFLAGS" \
        -DCMAKE_CXX_FLAGS="$SLKCFLAGS" \
        -DCMAKE_EXE_LINKER_FLAGS="$LDFLAGS -ldl" \
        -DCMAKE_DEFAULT_BUILD_TYPE="Release" \
        -DCMAKE_INSTALL_PREFIX="$_PREFIX" \
        -DLIB_SUFFIX="$LIBDIRSUFFIX" \
        -DMAN_INSTALL_DIR="$_PREFIX/man" \
        -DLauncher_BUILD_PLATFORM="slackware" \
        -DLauncher_ENABLE_JAVA_DOWNLOADER="ON" \
        -DBUILD_TESTING="OFF"
  cmake --build --preset linux

  DESTDIR=$PKG cmake --install build
  install -Dm644 -t $PKG/$_PREFIX/doc/$PRGNAM-$VERSION \
    CONTRIBUTING.md COPYING.md README.md LICENSE
}
