# Maintainer: Vladislav 'fsLeg' Borisov <fsleg at t-rg dot ws>

PRGNAM="fooyin"
VERSION="0.13.0"
BUILD="${BUILD:-1}"
DESCRIPTION="customisable music player"
HOMEPAGE="https://fooyin.org/"
DOWNLOAD="https://github.com/fooyin/fooyin/archive/v${VERSION}/${PRGNAM}-${VERSION}.tar.gz"
SHA256SUM="3cb8cd911a8a74a828fd58d12ea458f0ad0b9827a17430ae44bb71a97d926590"
REQUIRES=(qt6)
OPTIONAL=(KDSingleApplication libebur128 libgme libopenmpt soundtouch soxr)

unpack () {
  $UNTAR $CWD/$PRGNAM-$VERSION.tar.gz

  if [[ -d /usr/lib$LIBDIRSUFFIX/cmake/KDSingleApplication-qt6 && "$SLACKVER" != "current" ]];
                                     then REQUIRES+=(KDSingleApplication); fi
  if pkg-config --exists libebur128; then REQUIRES+=(libebur128); fi
  if pkg-config --exists libgme;     then REQUIRES+=(libgme); fi
  if pkg-config --exists libopenmpt; then REQUIRES+=(libopenmpt); fi
  if pkg-config --exists soundtouch; then REQUIRES+=(soundtouch); fi
  if pkg-config --exists soxr;       then REQUIRES+=(soxr); fi
}

build () {
  cmake -G Ninja \
        -B build \
        -DFETCH_PROJECTM="ON"
  cmake --build build

  DESTDIR=$PKG \
  cmake --install build \
        --prefix $_PREFIX

  rm -rf $PKG/$_PREFIX/{include,lib$LIBDIRSUFFIX/cmake}
  rm -rf $PKG/$_PREFIX/lib$LIBDIRSUFFIX/*.a

  install -Dm644 -t $PKG/$_PREFIX/doc/$PRGNAM-$VERSION CHANGELOG.md
  mv $PKG/$_PREFIX/share/doc/fooyin/* $PKG/$_PREFIX/doc/$PRGNAM-$VERSION
  rm -rf $PKG/$_PREFIX/share/doc
}
