# Maintainer: Vladislav 'fsLeg' Borisov <fsleg at t-rg dot ws>

PRGNAM="fooyin"
VERSION="0.11.0"
BUILD="${BUILD:-1}"
DESCRIPTION="customisable music player"
HOMEPAGE="https://fooyin.org/"
DOWNLOAD="https://github.com/fooyin/fooyin/archive/v${VERSION}/${PRGNAM}-${VERSION}.tar.gz"
SHA256SUM="0f4b582516e2c14791768fdf00874be1c0c935d87faffd95b9bfed8e91eaf5da"
REQUIRES="qt6"
OPTIONAL="KDSingleApplication libebur128 libgme libopenmpt soundtouch soxr"

unpack () {
  tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
}

build () {
  cmake -G Ninja \
        -B build
  cmake --build build

  DESTDIR=$PKG \
  cmake --install build \
        --prefix $_PREFIX

  rm -rf $PKG/$_PREFIX/{include,lib$LIBDIRSUFFIX/cmake}
  rm -rf $PKG/$_PREFIX/lib$LIBDIRSUFFIX/*.a

  install -Dm644 -t $PKG/$_PREFIX/doc/$PRGNAM-$VERSION CHANGELOG.md
  mv $PKG/$_PREFIX/share/doc/fooyin/* $PKG/$_PREFIX/doc/$PRGNAM-$VERSION
  rm -rf $PKG/$_PREFIX/share/doc
}
