# Maintainer: Vladislav 'fsLeg' Borisov <fsleg at t-rg dot ws>

PRGNAM="fooyin"
VERSION="0.10.1"
BUILD="${BUILD:-1}"
DESCRIPTION="customisable music player"
HOMEPAGE="https://fooyin.org/"
DOWNLOAD="https://github.com/fooyin/fooyin/archive/v${VERSION}/${PRGNAM}-${VERSION}.tar.gz"
SHA256SUM="32f3ff627612cd2d2d3ed8cb3d8a128f05079bdf5aa906b5c8bb5941707bd833"
REQUIRES="qt6"
OPTIONAL="KDSingleApplication libebur128 libgme libopenmpt soundtouch soxr"

unpack () {
  tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
}

build () {
  cmake -G Ninja \
        -B build
  cmake --build build

  DESTDIR=$PKG \
  cmake --install build \
        --prefix $_PREFIX

  rm -rf $PKG/$_PREFIX/{include,lib$LIBDIRSUFFIX/cmake}
  rm -rf $PKG/$_PREFIX/lib$LIBDIRSUFFIX/*.a

  install -Dm644 -t $PKG/$_PREFIX/doc/$PRGNAM-$VERSION CHANGELOG.md
  mv $PKG/$_PREFIX/share/doc/fooyin/* $PKG/$_PREFIX/doc/$PRGNAM-$VERSION
  rm -rf $PKG/$_PREFIX/share/doc
}
