# Maintainer: Vladislav 'fsLeg' Borisov <fsleg at t-rg dot ws>

PRGNAM="amneziawg-kernel"
TARNAM="amneziawg-linux-kernel-module"
VERSION="3.1.20260812"
BUILD="${BUILD:-1}"
DESCRIPTION="AmneziaWG Linux kernel module"
HOMEPAGE="https://github.com/amnezia-vpn/amneziawg-linux-kernel-module"
DOWNLOAD="https://github.com/amnezia-vpn/amneziawg-linux-kernel-module/archive/v${VERSION}/${TARNAM}-${VERSION}.tar.gz"
SHA256SUM="a85817876676d5933385712657bd5525a0a2939baaf057f68e3629c7b4553c82"
SUGGESTS="amneziawg-tools"
KERNEL="${KERNEL:-$(uname -r)}"
PKGVER="${VERSION//-/.}_${KERNEL//-/_}"

unpack () {
  $UNTAR $CWD/$TARNAM-$VERSION.tar.gz
  mv $TARNAM-$VERSION $PRGNAM-$VERSION

  if [[ ! -v USE_DKMS ]] && command -v dkms &> /dev/null; then
    USE_DKMS=yes
  fi

  if [[ "${USE_DKMS@L}" == "yes" ]]; then
    # Set version in dkms.conf and Makefile
    sed -i "s/^PACKAGE_NAME=.*/PACKAGE_NAME=\"$PRGNAM\"/
            s/^PACKAGE_VERSION=.*/PACKAGE_VERSION=\"$VERSION\"/" \
      $PRGNAM-$VERSION/src/dkms.conf
    sed -i "s/^WIREGUARD_VERSION = .*/WIREGUARD_VERSION = $VERSION/" \
      $PRGNAM-$VERSION/src/Makefile
    source $PRGNAM-$VERSION/src/dkms.conf

    # With DKMS the package is no longer tied to kernel version
    PKGVER=${VERSION//-/.}
  fi

  # fix building on 5.15.204+
  patch -p1 -d $PRGNAM-$VERSION -i $CWD/5.15.204.patch
}

build () {
  if [[ "${USE_DKMS@L}" == "yes" ]]; then
    KERNELRELEASE=$KERNEL \
    DESTDIR=$PKG \
      make -C src dkms-install
    install -Dm644 $CWD/dkms.doinst.sh $PKG/install/doinst.sh
    install -Dm644 $CWD/dkms.douninst.sh $PKG/install/douninst.sh
    sed -i "s|@VERSION@|$VERSION|g
            s|@BUILT_MODULE_NAME@|$BUILT_MODULE_NAME|g
            s|@DEST_MODULE_LOCATION@|${DEST_MODULE_LOCATION#/}|g" \
      $PKG/install/doinst.sh \
      $PKG/install/douninst.sh
  else
    KERNELRELEASE=$KERNEL \
      make -C src
    install -Dm644 -t $PKG/lib/modules/$KERNEL/kernel/net src/amneziawg.ko
    install -Dm644 -t $PKG/install $CWD/doinst.sh
    sed -i "s|@KERNEL@|$KERNEL|" $PKG/install/doinst.sh
    cp -a $PKG/install/doinst.sh $PKG/install/douninst.sh
  fi

  install -Dm644 -t $PKG/$_PREFIX/doc/$PRGNAM-$PKGVER \
    COPYING README.md
}
