# Maintainer: Vladislav 'fsLeg' Borisov <fsleg at t-rg dot ws>

PRGNAM="fdpowermon"
VERSION="1.20"
BUILD="${BUILD:-1}"
DESCRIPTION="simple battery power monitor for laptops with ACPI"
HOMEPAGE="https://github.com/yoe/fdpowermon"
DOWNLOAD="https://github.com/yoe/fdpowermon/archive/${PRGNAM}-${VERSION}/${PRGNAM}-${PRGNAM}-${VERSION}.tar.gz"
SHA256SUM="564c739fa5bab315fb588f540ec357073545f22ab7da99ac220e3b58a6c89471"
REQUIRES=(acpi perl-Gtk3)
ARCH="noarch"

unpack () {
  $UNTAR $CWD/$PRGNAM-$PRGNAM-$VERSION.tar.gz
  mv $PRGNAM-$PRGNAM-$VERSION $PRGNAM-$VERSION
}

build () {
  if [ ! "$_PREFIX" = "/usr" ]; then
    sed -i "s|/etc|$_PREFIX/etc|g" fdpowermon
  fi
  install -Dm755 -t $PKG/$_PREFIX/bin fdpowermon
  install -Dm644 -t $PKG/$SYSCONFDIR/$PRGNAM theme.cfg
  install -Dm644 -t $PKG/$_PREFIX/share/icons/oxygen/base/22x22/status/ icons/*.png
  install -d $PKG/$_PREFIX/man/man1
  pod2man < fdpowermon > $PKG/$_PREFIX/man/man1/fdpowermon.1
  install -Dm644 -t $PKG/$_PREFIX/doc/$PRGNAM-$VERSION debian/copyright debian/changelog README.md
  install -Dm644 -t $PKG/$_PREFIX/doc/$PRGNAM-$VERSION/examples theme.pl
}
