# Maintainer: Vladislav 'fsLeg' Borisov <fsleg at t-rg dot ws>

PRGNAM="gxkb"
VERSION="0.9.6"
BUILD="${BUILD:-1}"
DESCRIPTION="X11 keyboard indicator and switcher"
HOMEPAGE="https://zen-tools.github.io/gxkb/"
DOWNLOAD="https://github.com/zen-tools/${PRGNAM}/archive/v${VERSION}/${PRGNAM}-${VERSION}.tar.gz"
SHA256SUM="ab5a243c52ed1fb479ca1ed01d837d61deb246960691695deecaae4ad65b60c4"

unpack () {
  $UNTAR $CWD/$PRGNAM-$VERSION.tar.gz

  # Patch back Belorussian and Russian flags
  patch -p1 -d $PRGNAM-$VERSION < $CWD/by-ru-flags.patch
  cp $CWD/{by,ru}.png $PRGNAM-$VERSION/data/flags/
}

build () {
  ./autogen.sh
  ./configure \
    --prefix=$_PREFIX \
    --libdir=$_PREFIX/lib${LIBDIRSUFFIX} \
    --sysconfdir=$SYSCONFDIR \
    --localstatedir=$LOCALSTATEDIR \
    --mandir=$_PREFIX/man \
    --docdir=$_PREFIX/doc/$PRGNAM-$VERSION \
    --build=$ARCH-slackware-linux \
    --enable-appindicator=no
  make

  make install DESTDIR=$PKG
  install -Dm644 -t $PKG/$_PREFIX/doc/$PRGNAM-$VERSION README.md
}
