#!/bin/bash

# TODO: figure out how to check if the git mirror is proper as you
#       can't checksum a directory

# Do checks first

# Check for the SlackBuild
if [[ ! "${#@}" -eq 1 ]]; then
  echo "Usage: ${0} appname.SlackBuild"
  exit 1
elif [[ ! -f "${1}" ]]; then
  echo "${1} doesn't exist."
  exit 1
fi

# Check for fakeroot
for LPATH in ${LD_LIBRARY_PATH//:/ }; do
  if [[ "${LPATH}" == *libfakeroot ]]; then
    ROOT_TYPE="fakeroot"
  fi
done

if [[ "$(awk '{print $2}' /proc/self/uid_map)" != 0 ]]; then
  ROOT_TYPE="unshare"
  echo "You're using unshare. This is not supported."
fi

if [[ "${EUID}" = 0 ]]; then
  if [[ -z "${ROOT_TYPE}" && "${SB_USE_REAL_ROOT:-N}" == "N" ]]; then
    echo "You are using real root. This isn't recommended. Are you sure you want to continue?"
    read -p "Y/[N] " SB_USE_REAL_ROOT
    case "${SB_USE_REAL_ROOT}" in
      "n"|"N"|"") exit 1 ;;
    esac
  fi
elif (which fakeroot &> /dev/null); then
  exec fakeroot "${0}" "${1}"
else
  echo "You aren't using fakeroot environment."
  exit 1
fi

# Set the environment
TAG="sb"
PKGTYPE="txz"
TMP="${SB_TMP:-/tmp/sb}"
OUTPUT="${SB_OUTPUT:-/tmp}"
_PREFIX="${SB_PREFIX:-/usr/local}"

if [[ "${_PREFIX}" == "/usr" ]]; then
  SYSCONFDIR="/etc"
  LOCALSTATEDIR="/var"
else
  SYSCONFDIR="${_PREFIX}/etc"
  LOCALSTATEDIR="${_PREFIX}/var"
fi

if [[ -z "${ARCH}" ]]; then
  case "$(uname -m)" in
    i?86) ARCH="i586" ;;
    arm*) ARCH="arm" ;;
       *) ARCH="$(uname -m)" ;;
  esac
fi

if [[ "${SB_IGNORE_ARCH:-N}" == "N" && "${ARCH}" != "x86_64" ]]; then
  echo "You are using ${ARCH} architecture. This isn't supported. Are you sure you want to continue?"
  read -p "Y/[N] " SB_IGNORE_ARCH
  case "${SB_IGNORE_ARCH}" in
    "n"|"N"|"") exit 1 ;;
  esac
fi

# Nothing but x86_64 is supported here anymore, but keep it for
# possible compatibility
case "${ARCH}" in
  i?86)
    SLKCFLAGS="-O2 -march=${ARCH} -mtune=i686"
    LIBDIRSUFFIX=""
    DEBARCH="i386"
    PLATFORM="ia32"
    BITS="32"
    ;;
  "arm")
    SLKCFLAGS="-O2 -march=armv5te"
    LIBDIRSUFFIX=""
    DEBARCH="armhf"
    PLATFORM="arm"
    BITS="32"
    ;;
  "x86_64")
    SLKCFLAGS="-O2 -fPIC"
    LIBDIRSUFFIX="64"
    DEBARCH="amd64"
    PLATFORM="x64"
    BITS="64"
    ;;
  "aarch64")
    SLKCFLAGS="-O2 -march=${ARCH}"
    LIBDIRSUFFIX="64"
    DEBARCH="arm64"
    PLATFORM="arm64"
    BITS="64"
    ;;
  *)
    SLKCFLAGS="-O2 -march=${ARCH}"
    LIBDIRSUFFIX=""
    ;;
esac

SLACKVER="$(awk '{print $2}' /etc/slackware-version)"
if [[ "${SLACKVER: -1}" == "+" ]]; then
  SLACKVER="current"
fi

PYVER="$(python3 -c 'import sys; print("%d.%d" % sys.version_info[:2])')"

if ! echo $PATH | grep -q sbin; then
  export PATH="/usr/local/sbin:/usr/sbin:/sbin:${PATH}"
fi

# XDG directories
export XDG_CONFIG_HOME="${TMP}/.config"
export XDG_CONFIG_CACHE="${TMP}/.cache"
export XDG_CACHE_HOME="${XDG_CONFIG_CACHE}"

# Temporary directory
export TMPDIR="${TMP}/.tmp"
export TMP_DIR="${TMPDIR}"
mkdir -p "${TMPDIR}"

# pkg-config
export PKG_CONFIG_PATH="${_PREFIX}/lib${LIBDIRSUFFIX}/pkgconfig:${PKG_CONFIG_PATH}"
export PKG_CONFIG_SYSTEM_INCLUDE_PATH="${PKG_CONFIG_SYSTEM_INCLUDE_PATH}:/usr/include:${_PREFIX}/include"

# C and C++
export CFLAGS="${SLKCFLAGS} ${CFLAGS}"
export CXXFLAGS="${SLKCFLAGS} ${CXXFLAGS}"
export CCACHE_DIR="${XDG_CONFIG_CACHE}/ccache"
export LDFLAGS="-fuse-ld=$(for file in /usr/bin/ld.?old; do [[ -e "$file" ]] && awk -F'\\.' '{print $NF}' <<< "$file" || echo "bfd" && break; done) ${LDFLAGS}"

# NodeJS
export npm_config_cache="${XDG_CONFIG_CACHE}/npm"
export npm_config_nodedir="/usr"
export COREPACK_HOME="${TMP}/.corepack"

## Yarn
export YARN_CACHE_FOLDER="${XDG_CONFIG_CACHE}/yarn"

## PNPM
export PNPM_HOME="${XDG_CONFIG_CACHE}/pnpm"
mkdir -p "${XDG_CONFIG_HOME}/pnpm"
cat << EOF > "${XDG_CONFIG_HOME}/pnpm/rc"
store-dir="${XDG_CONFIG_CACHE}/pnpm/store"
EOF

# Rust
export RUSTFLAGS="-C target-cpu=native"
export CARGO_HOME="${TMP}/.cargo"
export PATH="/opt/rust/bin:${PATH}"
export LD_LIBRARY_PATH="/opt/rust/lib${LIBDIRSUFFIX}:${LD_LIBRARY_PATH}"

# Go
export CGO_ENABLED="1"
export CGO_CFLAGS="${CFLAGS}"
export CGO_CXXFLAGS="${CXXFLAGS}"
export CGO_CPPFLAGS="${CXXFLAGS}"
export GOPATH="${TMP}/.go"
export GOCACHE="${XDG_CONFIG_CACHE}/go"
export GOTMPDIR="${TMP}/.go"
mkdir -p "${GOTMPDIR}"

# Buf
export BUF_CACHE_DIR="${XDG_CONFIG_CACHE}/buf"

# Dart
export PUB_CACHE="${XDG_CONFIG_CACHE}/dart"

# Define useful functions
reset_permissions () {
  if [ -z "${1}" ]; then
    local DIR="$(pwd)"
  else
    local DIR="${1}"
  fi
  chown -R root:root "${DIR}"
  find "${DIR}" ! -type l -a \( \
    \(   -perm /111 -a ! -perm 755 -a -exec chmod -f 755 {} + \) -o \
    \( ! -perm /111 -a ! -perm 644 -a -exec chmod -f 644 {} + \) \
    \)
  }

compress_files () {
  if [ -z "${1}" ]; then
    local DIR="$(pwd)"
  else
    local DIR="${1}"
  fi
  find "${DIR}" -type f -exec gzip -9 {} \;
  for i in $(find "${DIR}" -type l); do
    ln -s "$(readlink "${i}").gz" "${i}.gz"
    rm "${i}"
  done
}

check_gid () {
  # Check if the group exists. If not, then bail.
  # Usage: check_gid group gid
  if [ -z "$(getent group "${1}")" ]; then
    echo "You must have a '${1}' group to run this script."
    echo "  # groupadd -g ${2} ${1}"
    exit 1
  fi
}

check_uid () {
  # Check if the user exists. If not, then bail. Assumes UID=GID
  # Usage: check_uid user uid
  if [ -z "$(getent passwd "${1}")" ]; then
    echo "You must have a '${1}' user to run this script."
    echo "  # useradd -r -u ${2} -g ${2} -s /sbin/nologin -M ${1}"
    exit 1
  fi
}

get_submodules () {
  if [[ -n "${1}" ]]; then
    local DIR="${1}"
  else
    local DIR="$(pwd)"
  fi

  if [[ -f "${DIR}/.gitmodules" ]]; then
    for SUBMODULE in $(git config -f "${DIR}/.gitmodules" --get-regexp '^submodule\..*\.path$' | awk '{print $2}'); do
      BRANCH="$(git config -f "${DIR}/.gitmodules" --get "submodule.${SUBMODULE}.branch" || true)"
      if [[ -n "${BRANCH}" ]]; then
        BRANCH="-b ${BRANCH}"
      fi
      git -C "${DIR}" clone --depth 1 ${BRANCH} "$(git config -f "${DIR}/.gitmodules" --get "submodule.${SUBMODULE}.url")" "${SUBMODULE}"
      unset -v BRANCH
      get_submodules "${DIR}/${SUBMODULE}"
    done
  fi
}

# Source the SlackBuild and start building

set -e
shopt -u sourcepath

source "${1}"

cd "$(dirname ${1})"; CWD="$(pwd)"
PKG="${TMP}/package-${PRGNAM}"
if [[ -z "${PKGVER}" ]]; then
  PKGVER="${VERSION}"
fi

rm -rf "${PKG}"
mkdir -p "${TMP}" "${PKG}" "${OUTPUT}"
rm -rf "${TMP}/${PRGNAM}-${VERSION}"

if [[ -n "${PRINT_PACKAGE_NAME}" ]]; then
  echo "${PRGNAM}-${PKGVER}-${ARCH}-${BUILD}${TAG}.${PKGTYPE}"
  exit 0
fi

# Retrieve the sources if they aren't present
for URL in ${DOWNLOAD}; do
  if [[ "${URL}" =~ ^git\+ ]]; then
    declare -A PARAMS
    IFS='&' read -ra PAIRS <<< "${URL#*#}"
    for PAIR in "${PAIRS[@]}"; do
        IFS='=' read -r KEY VALUE <<< "$PAIR"
        PARAMS["$KEY"]="$VALUE"
    done
    if [[ -n ${PARAMS["branch"]} ]]; then
      BRANCH="--branch ${PARAMS["branch"]}"
    fi
    URL="${URL%%#*}"
    if [[ -d "$(basename "${URL}")" ]]; then
      git -C "$(basename "${URL}")" fetch --all
    else
      git clone --mirror ${BRANCH} -- "${URL#git+}"
    fi
    unset PARAMS PAIRS KEY VALUE BRANCH
  elif [[ ! -f "$(basename "${URL}")" ]]; then
    wget --tries=inf --retry-on-http-error=503 "${URL}"
  fi
done

# Check if sources are correct
declare -a CHECKSUMS
SHA256SUMS=(${SHA256SUM})
TARBALLS=($(basename -a ${DOWNLOAD}))
for i in $(seq 1 "${#TARBALLS[@]}"); do
  i+=-1
  if [[ "${SHA256SUMS[${i}]}" =~ ^[a-f0-9]{64}$ ]]; then
    CHECKSUMS+="${SHA256SUMS[${i}]}  ${TARBALLS[$i]}\n"
  elif [[ "${SHA256SUMS[${i}]}" == "-" ]]; then
    continue
  else
    echo "Invalid checksum: ${SHA256SUMS[${i}]}"
    exit
  fi
done
if [[ "${#CHECKSUMS}" -gt 0 ]]; then
  sha256sum --check <(echo -e "${CHECKSUMS}")
fi
unset CHECKSUMS SHA256SUMS TARBALLS

cd "${TMP}"

# Some sources are packed weird, so let the script handle unpacking
# instead of trying to guess everything. This also allows for custom
# steps when preparing the source tree
unpack

# Specify full path in case directory was changed when unpacking
cd "${TMP}/${PRGNAM}-${VERSION}"

if [[ -z "${SKIP_PERMS}" ]]; then
  reset_permissions
fi

build

# Failsafe in case directory was changed during the build process
cd "${TMP}/${PRGNAM}-${VERSION}"

# Don't ship .la files:
rm -f "${PKG}"/{,$_PREFIX/}lib"${LIBDIRSUFFIX}"/*.la

# Strip binaries and libraries - this can be done with 'make install-strip'
# in many source trees
if [[ -z "${SKIP_STRIP}" ]]; then
  find "${PKG}" -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
    | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
fi
find ${PKG} -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs chmod a+x 2> /dev/null || true

# Compress man pages
if [[ -d "${PKG}${_PREFIX}/man" ]]; then
  compress_files "${PKG}${_PREFIX}/man"
fi

# Compress info pages and remove the package's dir file
if [[ -d "${PKG}${_PREFIX}/info" ]]; then
  rm -f "${PKG}${_PREFIX}/info/dir"
  find "${PKG}${_PREFIX}/info" -type f -name "*.info*" -exec gzip -9 {} \;
fi

# Remove perllocal.pod and other special files that don't need to be installed,
# as they will overwrite what's already on the system.  If this is not needed,
# remove it from the script.
# Remove 'special' files
find "${PKG}" -name perllocal.pod \
  -o -name ".packlist" \
  -o -name "*.bs" \
  | xargs rm -f

# Include the SlackBuild script in the documentation directory
mkdir -p "${PKG}${_PREFIX}/doc/${PRGNAM}-${PKGVER}"
cat "${CWD}/${PRGNAM}.SlackBuild" > "${PKG}${_PREFIX}/doc/${PRGNAM}-${PKGVER}/${PRGNAM}.SlackBuild"

# Copy the slack-desc (and a custom doinst.sh and douninst.sh if necessary) into ./install
mkdir -p "${PKG}/install"
for FILE in slack-desc doinst.sh douninst.sh; do
  if [[ -f "${CWD}/${FILE}" && ! -f "${PKG}/install/${FILE}" ]]; then
    cat "${CWD}/${FILE}" > "${PKG}/install/${FILE}"
  fi
done

# Add metadata for slapt-get to use
if [[ -n "${REQUIRES}" ]]; then
  echo "${REQUIRES}" | tr ' ' '\n' > "${PKG}/install/slack-required"
fi
if [[ -n "${CONFLICTS}" ]]; then
  echo "${CONFLICTS}" | tr ' ' '\n' > "${PKG}/install/slack-conflicts"
fi

# Make the package; be sure to leave it in $OUTPUT
# If package symlinks need to be created during install *before*
# your custom contents of doinst.sh runs, then add the -p switch to
# the makepkg command below -- see makepkg(8) for details
cd "${PKG}"
/sbin/makepkg -l y -c n "${OUTPUT}/${PRGNAM}-${PKGVER}-${ARCH}-${BUILD}${TAG}.${PKGTYPE}"

exit 0
