# Maintainer: Vladislav 'fsLeg' Borisov <fsleg at t-rg dot ws>

PRGNAM="gendesk"
VERSION="1.0.15"
BUILD="${BUILD:-1}"
DESCRIPTION="Generate .desktop files by specifying minimum information"
HOMEPAGE="https://gendesk.roboticoverlords.org/"
DOWNLOAD="https://github.com/xyproto/${PRGNAM}/releases/download/v${VERSION}/${PRGNAM}-${VERSION}.tar.xz"
SHA256SUM="0d33bf249322c8445a800be146b9c2f86cf3ede5fc18b894ffce257fdf709b99"
BUILD_REQUIRES="google-go-lang"

unpack () {
  tar xfv $CWD/$PRGNAM-$VERSION.tar.xz
}

build () {
  go build -v \
           -mod=vendor \
           -buildmode=pie \
           -modcacherw \
           -trimpath \
           -ldflags "-s \
                     -w \
                     -linkmode=external \
                     -extldflags '${LDFLAGS}'"

  install -Dm755 -t $PKG/$_PREFIX/bin $PRGNAM
  install -Dm644 -t $PKG/$_PREFIX/man/man1 $PRGNAM.1.gz
  install -Dm644 -t $PKG/$_PREFIX/share/pixmaps $PRGNAM.png

  install -Dm644 -t $PKG/$_PREFIX/doc/$PRGNAM-$VERSION \
    CHANGELOG.md LICENSE README.md
}
