# Maintainer: Vladislav 'fsLeg' Borisov <fsleg at t-rg dot ws>

PRGNAM="element-desktop-bin"
VERSION="1.12.27"
BUILD="${BUILD:-1}"
DESCRIPTION="Secure and independent communication via Matrix"
HOMEPAGE="https://element.io/"
DOWNLOAD="https://packages.element.io/debian/pool/main/e/${PRGNAM%-bin}/${PRGNAM%-bin}_${VERSION}_${DEBARCH}.deb"
SHA256SUM="0881fe504c53fcb954e391be29883f3dc5d88df2c4425605f0630b4d7d7638ac"
REQUIRES=(sqlcipher)
CONFLICTS=(element-desktop)

unpack () {
  mkdir $PRGNAM-$VERSION
  ar xv --output $PRGNAM-$VERSION $CWD/${PRGNAM%-bin}_${VERSION}_${DEBARCH}.deb data.tar.xz
}

build () {
  $UNTAR data.tar.xz -C $PKG
  install -Dm644 -t $PKG/$_PREFIX/doc/$PRGNAM-$VERSION \
    $PKG/usr/share/doc/${PRGNAM%-bin}/* $PKG/opt/Element/LICENSE*
  rm -rf $PKG/usr/share/doc
}
