# Maintainer: Vladislav 'fsLeg' Borisov <fsleg at t-rg dot ws>

PRGNAM="element-desktop-bin"
VERSION="1.12.25"
BUILD="${BUILD:-1}"
DESCRIPTION="Secure and independent communication via Matrix"
HOMEPAGE="https://element.io/"
DOWNLOAD="https://packages.element.io/debian/pool/main/e/${PRGNAM%-bin}/${PRGNAM%-bin}_${VERSION}_${DEBARCH}.deb"
SHA256SUM="97f6e2c901a537f8e215d6b59b1234d92b7ce6e39e706b8a78c7be6b23416158"
REQUIRES="sqlcipher"
CONFLICTS="element-desktop"

unpack () {
  mkdir $PRGNAM-$VERSION
  ar xv --output $PRGNAM-$VERSION $CWD/${PRGNAM%-bin}_${VERSION}_${DEBARCH}.deb data.tar.xz
}

build () {
  tar xvf data.tar.xz -C $PKG
  install -Dm644 -t $PKG/$_PREFIX/doc/$PRGNAM-$VERSION \
    $PKG/usr/share/doc/${PRGNAM%-bin}/* $PKG/opt/Element/LICENSE*
  rm -rf $PKG/usr/share/doc
}
