# Maintainer: Vladislav 'fsLeg' Borisov <fsleg at t-rg dot ws>

PRGNAM="buf"
VERSION="1.66.1"
BUILD="${BUILD:-1}"
DESCRIPTION="The best way of working with Protocol Buffers."
HOMEPAGE="https://buf.build/"
DOWNLOAD="https://github.com/bufbuild/buf/archive/v${VERSION}/${PRGNAM}-${VERSION}.tar.gz"
SHA256SUM="5e20cb1090244d81057bcea44b03acca845579f751753cec1dce8b9d08af5cba"
BUILD_REQUIRES="google-go-lang"
SKIP_PERMS=1

unpack () {
  tar xvf $CWD/$PRGNAM-$VERSION.tar.gz

  # Don't fetch another copy of a toolchain
  sed -i '/^toolchain/d' $PRGNAM-$VERSION/go.mod
}

build () {
  mkdir build
  go build -v \
    -buildmode=pie \
    -mod=readonly \
    -modcacherw \
    -ldflags "-compressdwarf=false \
              -linkmode external \
              -extldflags '${LDFLAGS}'" \
    -o build \
    ./cmd/...

  install -d build/manpages
  ./build/buf manpages build/manpages
  install -Dm755 -t $PKG/$_PREFIX/bin build/{buf,protoc-gen-buf-lint,protoc-gen-buf-breaking}
  install -Dm644 -t $PKG/$_PREFIX/man/man1 build/manpages/*
  install -Dm644 -t $PKG/$_PREFIX/doc/$PRGNAM-$VERSION CHANGELOG.md LICENSE README.md
}
