# Maintainer: Vladislav 'fsLeg' Borisov <fsleg at t-rg dot ws>

PRGNAM="buf"
VERSION="1.73.0"
BUILD="${BUILD:-1}"
DESCRIPTION="The best way of working with Protocol Buffers."
HOMEPAGE="https://buf.build/"
DOWNLOAD="https://github.com/bufbuild/buf/archive/v${VERSION}/${PRGNAM}-${VERSION}.tar.gz"
SHA256SUM="5b74e94416114ccfcef2692592150a5c8459a9cb6f94088d42341ac06c389a22"
BUILD_REQUIRES=(google-go-lang)

unpack () {
  $UNTAR $CWD/$PRGNAM-$VERSION.tar.gz

  # Don't fetch another copy of a toolchain
  sed -i '/^toolchain/d' $PRGNAM-$VERSION/go.mod
}

build () {
  mkdir build
  go build -v \
    -buildmode=pie \
    -mod=readonly \
    -modcacherw \
    -ldflags "-compressdwarf=false \
              -linkmode external \
              -extldflags '${LDFLAGS}'" \
    -o build \
    ./cmd/...

  install -d build/manpages
  ./build/buf manpages build/manpages
  install -Dm755 -t $PKG/$_PREFIX/bin build/{buf,protoc-gen-buf-lint,protoc-gen-buf-breaking}
  install -Dm644 -t $PKG/$_PREFIX/man/man1 build/manpages/*
  install -Dm644 -t $PKG/$_PREFIX/doc/$PRGNAM-$VERSION CHANGELOG.md LICENSE README.md
}
