# Maintainer: Vladislav 'fsLeg' Borisov <fsleg at t-rg dot ws>

PRGNAM="google-go-lang"
VERSION="1.26.6"
BUILD="${BUILD:-1}"
DESCRIPTION="Core compiler tools for the Go programming language"
HOMEPAGE="https://go.dev"
DOWNLOAD="https://go.dev/dl/go${VERSION}.src.tar.gz
          https://go.dev/dl/go1.25.13.src.tar.gz
          https://go.dev/dl/go1.23.12.src.tar.gz
          https://go.dev/dl/go1.21.13.src.tar.gz
          https://go.dev/dl/go1.19.13.src.tar.gz"
SHA256SUM="a0721c54c688901448d77ad9b3ec7ea7c474730755ff891382e92ecb93ff2cb1
           1d7e2f70b1ee9b93c7df8efcca71f5adcc6a59797a4336c2d10171bd4c174614
           e1cce9379a24e895714a412c7ddd157d2614d9edbe83a84449b6e1840b4f1226
           71fb31606a1de48d129d591e8717a63e0c5565ffba09a24ea9f899a13214c34d
           ccf36b53fb0024a017353c3ddb22c1f00bc7a8073c6aac79042da24ee34434d3"
GO_BOOTSTRAP=("1.19.13"
              "1.21.13"
              "1.23.12"
              "1.25.13")

unpack () {
  tar xvf $CWD/go$VERSION.src.tar.gz
  mv go $PRGNAM-$VERSION
  mkdir -p $PRGNAM-$VERSION/bootstrap
  GOROOT_FINAL=$_PREFIX/lib$LIBDIRSUFFIX/go$VERSION/go

  # https://go.dev/doc/install/source#go14
  GO_CUR_VER=$(go version | cut -d' ' -f3 | cut -d. -f2)
  if [[ "$GO_CUR_VER" -ge 17 && "$GO_CUR_VER" -lt 20 ]]; then
    GO_BOOTSTRAP=(${GO_BOOTSTRAP[@]:1})
  elif [[ "$GO_CUR_VER" -ge 20 && "$GO_CUR_VER" -lt 22 ]]; then
    GO_BOOTSTRAP=(${GO_BOOTSTRAP[@]:2})
  elif [[ "$GO_CUR_VER" -ge 22 && "$GO_CUR_VER" -lt 24 ]]; then
    GO_BOOTSTRAP=(${GO_BOOTSTRAP[@]:3})
  elif [[ "$GO_CUR_VER" -ge 24 ]]; then
    unset GO_BOOTSTRAP
  fi

  if [[ -v GO_BOOTSTRAP[@] ]]; then
    for GO_VER in ${GO_BOOTSTRAP[@]}; do
      tar xvf $CWD/go$GO_VER.src.tar.gz -C $PRGNAM-$VERSION/bootstrap
      mv $PRGNAM-$VERSION/bootstrap/go $PRGNAM-$VERSION/bootstrap/go$GO_VER
    done
  fi
}

build () {
  if [[ -v GO_BOOTSTRAP[@] ]]; then
    i=0
    for GO_VER in ${GO_BOOTSTRAP[@]}; do
      if [[ ! -v GOROOT ]]; then
        if [[ "$i" -eq 0 ]]; then
          export GOROOT_BOOTSTRAP=/usr
        else
          export GOROOT_BOOTSTRAP=$(realpath bootstrap/go${GO_BOOTSTRAP[$(($i-1))]})
        fi
      fi
      pushd bootstrap/go$GO_VER/src
        bash make.bash
      popd
      unset GOROOT GOROOT_BOOTSTRAP
      i=$((++i))
    done
    export GOROOT_BOOTSTRAP=$(realpath bootstrap/go${GO_BOOTSTRAP[-1]})
  fi
  pushd src
    bash make.bash
  popd

  install -d $PKG/$GOROOT_FINAL \
             $PKG/$_PREFIX/doc/$PRGNAM-$VERSION \
             $PKG/install
  cp -aR -t $PKG/$GOROOT_FINAL \
    api/ bin/ lib/ misc/ pkg/ src/ test/ go.env
  find $PKG/$GOROOT_FINAL/src -type d -name "testdata" -exec rm -rf {} +
  find $PKG/$GOROOT_FINAL/src -type f -name "*_test.go" -exec rm -rf {} +
  install -Dm755 -t $PKG/$SYSCONFDIR/profile.d $CWD/go.{,c}sh
  sed -i "s|@GOROOT_FINAL@|$GOROOT_FINAL|g" \
      $PKG/$SYSCONFDIR/profile.d/go.{,c}sh

  cp -aR -t $PKG/$_PREFIX/doc/$PRGNAM-$VERSION \
    CONTRIBUTING.md LICENSE PATENTS README.md SECURITY.md VERSION doc/
}
