# Maintainer: Vladislav 'fsLeg' Borisov <fsleg at t-rg dot ws>

PRGNAM="3proxy"
VERSION="0.9.6"
BUILD="${BUILD:-1}"
DESCRIPTION="tiny free proxy server"
HOMEPAGE="https://3proxy.org/"
DOWNLOAD="https://github.com/3proxy/3proxy/archive/${VERSION}/${PRGNAM}-${VERSION}.tar.gz"
SHA256SUM="5645111fb146faaaf260c27f0e07e510e8530a7e8a18369474cc8abbedbc9c9a"

unpack () {
  check_gid proxy 396
  check_uid proxy 396
  tar xfv $CWD/$PRGNAM-$VERSION.tar.gz
}

build () {
  cmake \
    -DCMAKE_INSTALL_PREFIX=$_PREFIX \
    -DCMAKE_BUILD_TYPE=Release \
    -B build
  cmake --build build

  DESTDIR=$PKG cmake --install build

  # cmake doesn't install chroot (yet), so we'll do it manually
  install -dm550 -o proxy -g proxy $PKG/$LOCALSTATEDIR/lib/$PRGNAM/{,conf}
  install -dm755 -o proxy -g proxy $PKG/$LOCALSTATEDIR/lib/$PRGNAM/{logs,count,libexec}
  install -m755 -o proxy -g proxy -t $PKG/$LOCALSTATEDIR/lib/$PRGNAM/libexec build/bin/*.ld.so
  rm -r $PKG/etc $PKG/$_PREFIX/bin/{add3proxyuser.sh,postinstall.sh}
  install -d $PKG/$SYSCONFDIR/$PRGNAM
  sed "s|/bin|$_PREFIX/bin|
       s|/usr/local/$PRGNAM|$LOCALSTATEDIR/lib/$PRGNAM|
       s|\#daemon|daemon|
       /daemon/apidfile $LOCALSTATEDIR/run/$PRGNAM/$PRGNAM.pid" \
       scripts/3proxy.cfg.chroot > $PKG/$SYSCONFDIR/$PRGNAM/3proxy.cfg.new
  chmod 0644 $PKG/$SYSCONFDIR/$PRGNAM/3proxy.cfg.new
  install -Dm440 -o proxy -g proxy scripts/3proxy.cfg $PKG/$LOCALSTATEDIR/lib/$PRGNAM/conf/3proxy.cfg.new
  touch $PKG/$LOCALSTATEDIR/lib/$PRGNAM/conf/{counters.new,bandlimiters.new,passwd.new}
  chown proxy:proxy $PKG/$LOCALSTATEDIR/lib/$PRGNAM/conf/{counters.new,bandlimiters.new,passwd.new}
  chmod 0440 $PKG/$LOCALSTATEDIR/lib/$PRGNAM/conf/{counters.new,bandlimiters.new,passwd.new}
  sed "s|/etc|$SYSCONFDIR|g
       s|/bin|$_PREFIX/bin|" \
       scripts/add3proxyuser.sh > $PKG/$LOCALSTATEDIR/lib/$PRGNAM/conf/add3proxyuser.sh
  chown proxy:proxy $PKG/$LOCALSTATEDIR/lib/$PRGNAM/conf/add3proxyuser.sh
  chmod 0550 $PKG/$LOCALSTATEDIR/lib/$PRGNAM/conf/add3proxyuser.sh
  ln -sf ../../${LOCALSTATEDIR#$_PREFIX}/lib/$PRGNAM/conf $PKG/$SYSCONFDIR/$PRGNAM/
  install -d $PKG/$LOCALSTATEDIR/log/$PRGNAM
  ln -sf ../../../${LOCALSTATEDIR#$_PREFIX}/lib/$PRGNAM/logs $PKG/$LOCALSTATEDIR/log/$PRGNAM/
  mv $PKG/$_PREFIX/share/man $PKG/$_PREFIX
  rmdir $PKG/$_PREFIX/share
  install -d $PKG/$LOCALSTATEDIR/run/$PRGNAM $PKG/$SYSCONFDIR/rc.d
  sed "s|@PREFIX@|$_PREFIX|g
       s|@SYSCONFDIR@|$SYSCONFDIR|g
       s|@LOCALSTATEDIR@|$LOCALSTATEDIR|g" \
       $CWD/rc.$PRGNAM > $PKG/$SYSCONFDIR/rc.d/rc.$PRGNAM.new
  chmod 0755 $PKG/$SYSCONFDIR/rc.d/rc.$PRGNAM.new

  # proxy conflicts with libproxy, so we rename it
  mv $PKG/$_PREFIX/bin/proxy $PKG/$_PREFIX/bin/htproxy
  mv $PKG/$_PREFIX/man/man8/proxy.8 $PKG/$_PREFIX/man/man8/htproxy.8

  install -d $PKG/$_PREFIX/doc/$PRGNAM-$VERSION/ru
  iconv -f koi8-r -t utf-8 -o $PKG/$_PREFIX/doc/$PRGNAM-$VERSION/ru/example1.txt doc/ru/example1.txt
  iconv -f koi8-r -t utf-8 -o $PKG/$_PREFIX/doc/$PRGNAM-$VERSION/ru/iodbc.txt doc/ru/iodbc.txt
  cp -anR -t $PKG/$_PREFIX/doc/$PRGNAM-$VERSION \
            authors copying README doc/{html,ru}/ cfg/
  install -d $PKG/install
  sed "s|@SYSCONFDIR@|${SYSCONFDIR#/}|g
       s|@LOCALSTATEDIR@|${LOCALSTATEDIR#/}|g" \
       $CWD/doinst.sh > $PKG/install/doinst.sh
}
