# Maintainer: Vladislav 'fsLeg' Borisov <fsleg at t-rg dot ws>

PRGNAM="3proxy"
VERSION="0.9.8"
BUILD="${BUILD:-1}"
DESCRIPTION="tiny free proxy server"
HOMEPAGE="https://3proxy.org/"
DOWNLOAD="https://github.com/3proxy/3proxy/archive/${VERSION}/${PRGNAM}-${VERSION}.tar.gz"
SHA256SUM="9f65f6d112560040bac075071703b059bfc7df57db8f4aa81e5f139898e628db"

unpack () {
  check_gid proxy 396
  check_uid proxy 396
  $UNTAR $CWD/$PRGNAM-$VERSION.tar.gz
}

build () {
  cmake \
    -DCMAKE_INSTALL_PREFIX=$_PREFIX \
    -DCMAKE_INSTALL_MANDIR=$_PREFIX/man \
    -DCMAKE_BUILD_TYPE=Release \
    -B build
  cmake --build build

  DESTDIR=$PKG cmake --install build

  # cmake doesn't install chroot (yet), so we'll do it manually
  install -dm550 -o proxy -g proxy $PKG/$LOCALSTATEDIR/lib/$PRGNAM/{,conf}
  install -dm755 -o proxy -g proxy $PKG/$LOCALSTATEDIR/lib/$PRGNAM/{logs,count,libexec}
  install -m755 -o proxy -g proxy -t $PKG/$LOCALSTATEDIR/lib/$PRGNAM/libexec build/bin/*.ld.so
  install -d $PKG/$SYSCONFDIR/$PRGNAM
  sed "s|/bin|$_PREFIX/bin|
       s|/usr/local/$PRGNAM|$LOCALSTATEDIR/lib/$PRGNAM|
       s|\#daemon|daemon|
       /daemon/apidfile $LOCALSTATEDIR/run/$PRGNAM/$PRGNAM.pid" \
       scripts/3proxy.cfg.chroot > $PKG/$SYSCONFDIR/$PRGNAM/3proxy.cfg.new
  chmod 0644 $PKG/$SYSCONFDIR/$PRGNAM/3proxy.cfg.new
  install -Dm440 -o proxy -g proxy build/3proxy.cfg $PKG/$LOCALSTATEDIR/lib/$PRGNAM/conf/3proxy.cfg.new
  rm -rf $PKG/$_PREFIX/$SYSCONFDIR \
         $PKG/$SYSCONFDIR/init.d \
         $PKG/opt
  touch $PKG/$LOCALSTATEDIR/lib/$PRGNAM/conf/{counters.new,bandlimiters.new,passwd.new}
  chown proxy:proxy $PKG/$LOCALSTATEDIR/lib/$PRGNAM/conf/{counters.new,bandlimiters.new,passwd.new}
  chmod 0440 $PKG/$LOCALSTATEDIR/lib/$PRGNAM/conf/{counters.new,bandlimiters.new,passwd.new}
  ln -sf ../../${LOCALSTATEDIR#$_PREFIX}/lib/$PRGNAM/conf $PKG/$SYSCONFDIR/$PRGNAM/
  install -d $PKG/$LOCALSTATEDIR/log/$PRGNAM
  ln -sf ../../../${LOCALSTATEDIR#$_PREFIX}/lib/$PRGNAM/logs $PKG/$LOCALSTATEDIR/log/$PRGNAM/
  install -d $PKG/$LOCALSTATEDIR/run/$PRGNAM $PKG/$SYSCONFDIR/rc.d
  sed "s|@PREFIX@|$_PREFIX|g
       s|@SYSCONFDIR@|$SYSCONFDIR|g
       s|@LOCALSTATEDIR@|$LOCALSTATEDIR|g" \
       $CWD/rc.$PRGNAM > $PKG/$SYSCONFDIR/rc.d/rc.$PRGNAM.new
  chmod 0755 $PKG/$SYSCONFDIR/rc.d/rc.$PRGNAM.new

  install -d $PKG/$_PREFIX/doc/$PRGNAM-$VERSION/ru
  iconv -f koi8-r -t utf-8 -o $PKG/$_PREFIX/doc/$PRGNAM-$VERSION/ru/example1.txt doc/ru/example1.txt
  iconv -f koi8-r -t utf-8 -o $PKG/$_PREFIX/doc/$PRGNAM-$VERSION/ru/iodbc.txt doc/ru/iodbc.txt
  cp -aR --update=none -t $PKG/$_PREFIX/doc/$PRGNAM-$VERSION \
    authors copying README.md doc/{html,ru}/ cfg/
  install -d $PKG/install
  sed "s|@SYSCONFDIR@|${SYSCONFDIR#/}|g
       s|@LOCALSTATEDIR@|${LOCALSTATEDIR#/}|g" \
       $CWD/doinst.sh > $PKG/install/doinst.sh
}
