# Maintainer: Vladislav 'fsLeg' Borisov <fsleg at t-rg dot ws>

PRGNAM="vips"
VERSION="8.18.5"
BUILD="${BUILD:-1}"
DESCRIPTION="fast image processing library with low memory needs"
HOMEPAGE="https://www.libvips.org/"
DOWNLOAD="https://github.com/libvips/libvips/releases/download/v${VERSION}/${PRGNAM}-${VERSION}.tar.xz"
SHA256SUM="8c4e6332d818249ed05ce98e36e6ed8a08e3249ac70f69680842ab2e5fee8510"
OPTIONAL="libspng highway matio libjxl libheif gi-docgen"

unpack () {
  $UNTAR $CWD/$PRGNAM-$VERSION.tar.xz
}

build () {
  if [ "${DOCS:-no}" != "no" ]; then
    DOCS=true
  else
    DOCS=false
  fi

  mkdir build
  meson setup \
    --buildtype=release \
    --libdir=$_PREFIX/lib${LIBDIRSUFFIX} \
    --localstatedir=$LOCALSTATEDIR \
    --mandir=$_PREFIX/man \
    --prefix=$_PREFIX \
    --sysconfdir=$SYSCONFDIR \
    -Ddocs=$DOCS \
    build
  meson compile -C build

  meson install --destdir=$PKG -C build
  install -Dm644 -t $PKG/$_PREFIX/doc/$PRGNAM-$VERSION \
    CITATION.cff CODE_OF_CONDUCT.md CONTRIBUTING.md ChangeLog LICENSE README.md
  if [ "${DOCS}" == "true" ]; then
    mv $PKG/$_PREFIX/share/doc/vips $PKG/$_PREFIX/doc/$PRGNAM-$VERSION/html
    rmdir $PKG/$_PREFIX/share/doc
  fi
}
