# Maintainer: Vladislav 'fsLeg' Borisov <fsleg at t-rg dot ws>

PRGNAM="vips"
VERSION="8.18.6"
BUILD="${BUILD:-1}"
DESCRIPTION="fast image processing library with low memory needs"
HOMEPAGE="https://www.libvips.org/"
DOWNLOAD="https://github.com/libvips/libvips/releases/download/v${VERSION}/${PRGNAM}-${VERSION}.tar.xz"
SHA256SUM="3c41e1d5458081bfa4a5bc54e116c46259c75c6760a18027764555632b9dda3e"
OPTIONAL=(gi-docgen highway libheif libjxl libspng matio)

unpack () {
  $UNTAR $CWD/$PRGNAM-$VERSION.tar.xz

  if [ "${DOCS:-no}" != "no" ]; then
    DOCS=true
  else
    DOCS=false
  fi

  if pkg-config --exists libhwy;  then REQUIRES+=(highway); fi
  if pkg-config --exists libheif; then REQUIRES+=(libheif); fi
  if pkg-config --exists libjxl;  then REQUIRES+=(libjxl); fi
  if pkg-config --exists libspng; then REQUIRES+=(libspng); fi
  if pkg-config --exists matio;   then REQUIRES+=(matio); fi
}

build () {
  mkdir build
  meson setup \
    --buildtype=release \
    --libdir=$_PREFIX/lib${LIBDIRSUFFIX} \
    --localstatedir=$LOCALSTATEDIR \
    --mandir=$_PREFIX/man \
    --prefix=$_PREFIX \
    --sysconfdir=$SYSCONFDIR \
    -Ddocs=$DOCS \
    build
  meson compile -C build

  meson install --destdir=$PKG -C build
  install -Dm644 -t $PKG/$_PREFIX/doc/$PRGNAM-$VERSION \
    CITATION.cff CODE_OF_CONDUCT.md CONTRIBUTING.md ChangeLog LICENSE README.md
  if [ "${DOCS}" == "true" ]; then
    mv $PKG/$_PREFIX/share/doc/vips $PKG/$_PREFIX/doc/$PRGNAM-$VERSION/html
    rmdir $PKG/$_PREFIX/share/doc
  fi
}
