# Maintainer: Vladislav 'fsLeg' Borisov <fsleg at t-rg dot ws>

PRGNAM="yubioath-desktop-bin"
TARNAM="yubico-authenticator"
VERSION="${VERSION:-7.3.0}"
BUILD="${BUILD:-1}"
DESCRIPTION="Yubico Authenticator for Desktop"
HOMEPAGE="https://www.yubico.com/products/yubico-authenticator/"
DOWNLOAD="https://developers.yubico.com/yubioath-flutter/Releases/${TARNAM}-${VERSION}-linux.tar.gz"
SHA256SUM="a82aa86a60f16d2d6bb07789f33d3256e12b7d2f231a0d6625dea1706c4069e1"
DOWNLOAD_x86="UNSUPPORTED"
REQUIRES="pcsc-lite ccid"

unpack () {
  tar xvf $CWD/$TARNAM-$VERSION-linux.tar.gz
  mv $TARNAM-$VERSION-linux $PRGNAM-$VERSION
}

build () {
  install -d $PKG/opt/${PRGNAM%-bin}
  cp -aR -t $PKG/opt/${PRGNAM%-bin} data/ helper/ lib/ linux_support/ authenticator
  install -Dm644 -t $PKG/$_PREFIX/share/applications linux_support/com.yubico.yubioath.desktop
  sed -i "s|@EXEC_PATH|/opt/${PRGNAM%-bin}|g" $PKG/$_PREFIX/share/applications/com.yubico.yubioath.desktop
  install -d $PKG/$_PREFIX/bin
  cat << EOF > $PKG/$_PREFIX/bin/authenticator
#!/bin/sh
/opt/${PRGNAM%-bin}/authenticator $@
EOF
  chmod 755 $PKG/$_PREFIX/bin/authenticator
  install -Dm644 -t $PKG/$_PREFIX/doc/$PRGNAM-$VERSION README.adoc
}
