# Maintainer: Vladislav 'fsLeg' Borisov <fsleg at t-rg dot ws>

PRGNAM="yubico-authenticator-bin"
PRGNAME="${PRGNAM%-bin}"
VERSION="7.4.1"
BUILD="${BUILD:-1}"
DESCRIPTION="Yubico Authenticator for Desktop"
HOMEPAGE="https://www.yubico.com/products/yubico-authenticator/"
DOWNLOAD="https://developers.yubico.com/yubioath-flutter/Releases/${PRGNAME}-${VERSION}-linux.tar.gz"
SHA256SUM="5c8f49cf3653ae9dd3911b53ca60475b03c8c957eb7385b1bd3d49ec4767ddac"
REQUIRES="pcsc-lite ccid"

unpack () {
  $UNTAR $CWD/$PRGNAME-$VERSION-linux.tar.gz
  mv $PRGNAME-$VERSION-linux $PRGNAM-$VERSION
}

build () {
  install -d $PKG/opt/${PRGNAME}
  cp -aR -t $PKG/opt/${PRGNAME} data/ helper/ lib/ linux_support/ authenticator
  install -Dm644 -t $PKG/$_PREFIX/share/applications linux_support/com.yubico.yubioath.desktop
  sed -i "s|@EXEC_PATH|/opt/${PRGNAME}|g" $PKG/$_PREFIX/share/applications/com.yubico.yubioath.desktop
  install -d $PKG/$_PREFIX/bin
  cat << EOF > $PKG/$_PREFIX/bin/authenticator
#!/bin/sh
/opt/${PRGNAME}/authenticator $@
EOF
  chmod 755 $PKG/$_PREFIX/bin/authenticator
  install -Dm644 -t $PKG/$_PREFIX/doc/$PRGNAM-$VERSION README.adoc
}
