# Maintainer: Vladislav 'fsLeg' Borisov <fsleg at t-rg dot ws>

PRGNAM="dart-sass"
VERSION="1.102.0"
EMBEDDED_PROTOCOL_VERSION="3.2.0"
BUILD="${BUILD:-1}"
DESCRIPTION="Dart implementation of Sass"
HOMEPAGE="https://sass-lang.com/dart-sass"
DOWNLOAD="https://github.com/sass/dart-sass/archive/${VERSION}/${PRGNAM}-${VERSION}.tar.gz \
          https://github.com/sass/sass/archive/embedded-protocol-${EMBEDDED_PROTOCOL_VERSION}/sass-embedded-protocol-${EMBEDDED_PROTOCOL_VERSION}.tar.gz"
SHA256SUM="7867797ec39c436462407eb3dc83555a7b8d157009838054bdbcd675f9857f14
           4e1f81684bc1666f03e52ddc790d0c2c22d99a5313fa2efe1dde4a5b5733c186"
BUILD_REQUIRES="buf dart-sdk"
SKIP_STRIP="1"

unpack () {
  tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
  tar xvf $CWD/sass-embedded-protocol-$EMBEDDED_PROTOCOL_VERSION.tar.gz -C $PRGNAM-$VERSION
  mkdir -p $PRGNAM-$VERSION/build
  mv $PRGNAM-$VERSION/sass-embedded-protocol-$EMBEDDED_PROTOCOL_VERSION $PRGNAM-$VERSION/build/language
}

build () {
  dart --disable-analytics
  dart pub get
  UPDATE_SASS_PROTOCOL=false \
    dart run grinder protobuf
  dart compile exe \
       -Dversion=$VERSION \
       -Ddart-version=$(dart --version | cut -d' ' -f4) \
       -Dprotocol-version=$EMBEDDED_PROTOCOL_VERSION \
       -Dcompiler-version=$VERSION \
       -o sass \
       bin/sass.dart

  install -Dm755 -t $PKG/$_PREFIX/bin sass
  install -Dm644 -t $PKG/$_PREFIX/doc/$PRGNAM-$VERSION \
    README.md AUTHORS CHANGELOG.md CONTRIBUTING.md LICENSE
}

