# Maintainer: Vladislav 'fsLeg' Borisov <fsleg at t-rg dot ws>

PRGNAM="amneziawg-tools"
VERSION="1.0.20250903"
BUILD="${BUILD:-1}"
DESCRIPTION="Tools for configuring AmneziaWG"
HOMEPAGE="https://github.com/amnezia-vpn/amneziawg-tools"
DOWNLOAD="https://github.com/amnezia-vpn/amneziawg-tools/archive/v${VERSION}/${PRGNAM}-${VERSION}.tar.gz"
SHA256SUM="d729a6f54aafcd55b2cbb7324f09ca8f0d2536772970652bf822a271d0c907d7"

unpack () {
  tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
}

build () {
  make -C src

  PREFIX=$_PREFIX \
  LIBDIR=$_PREFIX/lib${LIBDIRSUFFIX} \
  MANDIR=$_PREFIX/man \
  WITH_BASHCOMPLETION=yes \
  WITH_WGQUICK=yes \
  WITH_SYSTEMDUNITS=no \
  DESTDIR=$PKG \
  make -C src install

  install -d $PKG/$_PREFIX/doc/$PRGNAM-$VERSION
  cp -aR -t $PKG/$_PREFIX/doc/$PRGNAM-$VERSION \
    COPYING README.md contrib/
}
