# Maintainer: Vladislav 'fsLeg' Borisov <fsleg at t-rg dot ws>

PRGNAM="amneziawg-tools"
VERSION="3.0.20260805"
BUILD="${BUILD:-1}"
DESCRIPTION="Tools for configuring AmneziaWG"
HOMEPAGE="https://github.com/amnezia-vpn/amneziawg-tools"
DOWNLOAD="https://github.com/amnezia-vpn/amneziawg-tools/archive/v${VERSION}/${PRGNAM}-${VERSION}.tar.gz"
SHA256SUM="ac0966e4cab36bf40c7a621d269c47d94bd153b3fc3f205b371dd0f21d54f36d"
PKGVER="${VERSION//-/.}"

unpack () {
  tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
}

build () {
  make -C src

  PREFIX=$_PREFIX \
  LIBDIR=$_PREFIX/lib${LIBDIRSUFFIX} \
  MANDIR=$_PREFIX/man \
  WITH_BASHCOMPLETION=yes \
  WITH_WGQUICK=yes \
  WITH_SYSTEMDUNITS=no \
  DESTDIR=$PKG \
  make -C src install

  install -d $PKG/$_PREFIX/doc/$PRGNAM-$PKGVER
  cp -aR -t $PKG/$_PREFIX/doc/$PRGNAM-$PKGVER \
    COPYING README.md contrib/
}
