# Maintainer: Vladislav 'fsLeg' Borisov <fsleg at t-rg dot ws>

PRGNAM="amneziawg-tools"
VERSION="1.0.20260618"
BUILD="${BUILD:-1}"
DESCRIPTION="Tools for configuring AmneziaWG"
HOMEPAGE="https://github.com/amnezia-vpn/amneziawg-tools"
DOWNLOAD="https://github.com/amnezia-vpn/amneziawg-tools/archive/v${VERSION}/${PRGNAM}-${VERSION}.tar.gz"
SHA256SUM="f1993084634bb9e957d0b14756e019a4af2f4e9c08d73362cce3ab14cb92ea7b"

unpack () {
  tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
}

build () {
  make -C src

  PREFIX=$_PREFIX \
  LIBDIR=$_PREFIX/lib${LIBDIRSUFFIX} \
  MANDIR=$_PREFIX/man \
  WITH_BASHCOMPLETION=yes \
  WITH_WGQUICK=yes \
  WITH_SYSTEMDUNITS=no \
  DESTDIR=$PKG \
  make -C src install

  install -d $PKG/$_PREFIX/doc/$PRGNAM-$VERSION
  cp -aR -t $PKG/$_PREFIX/doc/$PRGNAM-$VERSION \
    COPYING README.md contrib/
}
