# Maintainer: Vladislav 'fsLeg' Borisov <fsleg at t-rg dot ws>

PRGNAM="element-desktop"
WEBNAM="element-web"
VERSION="1.12.26"
BUILD="${BUILD:-1}"
DESCRIPTION="secure and independent communication via Matrix"
HOMEPAGE="https://element.io/"
DOWNLOAD="https://github.com/element-hq/$WEBNAM/archive/v$VERSION/$WEBNAM-$VERSION.tar.gz"
SHA256SUM="eac91495ff4f56bbcf7e263d7ad779f08fa1698aa168784171ea4222b9ce4133"
REQUIRES=(sqlcipher)
BUILD_REQUIRES=(rust-opt "nodejs|nodejs22|nodejs24-bin")
CONFLICTS=(element-desktop-bin)

unpack () {
  $UNTAR $CWD/$WEBNAM-$VERSION.tar.gz
  mv $WEBNAM-$VERSION $PRGNAM-$VERSION

  corepack install --global \
    $(node -p "p=require('./$PRGNAM-$VERSION/package.json').devEngines.packageManager;p.name+'@'+p.version.split('+')[0]") \
    "yarn@^1"
  mkdir -p $COREPACK_HOME/bin
  corepack enable --install-directory $COREPACK_HOME/bin
  export PATH="$COREPACK_HOME/bin:$PATH"
  export NX_TUI=false
}

build () {
  pnpm install --frozen-lockfile
  VERSION=$VERSION \
    pnpm -C apps/web run build

  cd apps/desktop
  mkdir -p deploys
  mv ../web/webapp deploys/element-v$VERSION
  pnpm install --frozen-lockfile
  pnpm run fetch --noverify --cfgdir ""
  CRATE_CC_NO_DEFAULTS=1 \
    pnpm run build:native
  pnpm run build --publish never

  install -d $PKG/$_PREFIX/{bin,lib$LIBDIRSUFFIX,share/applications}
  cp -aR dist/linux-unpacked $PKG/$_PREFIX/lib$LIBDIRSUFFIX/$PRGNAM
  install -Dm644 $CWD/element-desktop.desktop $PKG/$_PREFIX/share/applications/io.element.Element.desktop
  sed -i "s|@PREFIX@|$_PREFIX|" $PKG/$_PREFIX/share/applications/io.element.Element.desktop
  ln -s $_PREFIX/lib$LIBDIRSUFFIX/element-desktop/element-desktop $PKG/$_PREFIX/bin/
  for geometry in 16x16 24x24 32x32 48x48 64x64 96x96 128x128 256x256 512x512; do
    install -d $PKG/$_PREFIX/share/icons/hicolor/$geometry/apps
    magick build/icon.png -resize $geometry $PKG/$_PREFIX/share/icons/hicolor/$geometry/apps/$PRGNAM.png
  done
  install -Dm644 -t $PKG/$_PREFIX/doc/$PRGNAM-$VERSION \
    CHANGELOG.md README.md ../../{AUTHORS.rst,CONTRIBUTING.md,LICENSE-*}
}
