# Maintainer: Vladislav 'fsLeg' Borisov <fsleg at t-rg dot ws>

PRGNAM="element-desktop"
WEBNAM="element-web"
VERSION="1.12.10"
BUILD="${BUILD:-1}"
DESCRIPTION="secure and independent communication via Matrix"
HOMEPAGE="https://element.io/"
DOWNLOAD="https://github.com/element-hq/${PRGNAM}/archive/v${VERSION}/${PRGNAM}-${VERSION}.tar.gz \
          https://github.com/element-hq/${WEBNAM}/archive/v$VERSION/${WEBNAM}-$VERSION.tar.gz"
SHA256SUM="2aa491d4601b0af20c36fff0133ea19a3585b16d9217d3ec9df9fe256d6167dd \
           17f6253497879f70f9c23729a25d77f0259ec7a9a43a33eeaebc45686922912b"
DOWNLOAD_x86="UNSUPPORTED"
REQUIRES="sqlcipher"
BUILD_REQUIRES="rust-opt nodejs|nodejs22|nodejs24-bin yarn"
CONFLICTS="element-desktop-bin"

unpack () {
  mkdir $PRGNAM-$VERSION
  tar xvf $CWD/$PRGNAM-$VERSION.tar.gz -C $PRGNAM-$VERSION
  tar xvf $CWD/$WEBNAM-$VERSION.tar.gz -C $PRGNAM-$VERSION
}

build () {
  cd $WEBNAM-$VERSION
  yarn install --frozen-lockfile \
               --ignore-engines \
               --no-fund \
               --update-checksums
  VERSION=$VERSION \
    yarn build

  cd ../$PRGNAM-$VERSION
  mkdir -p deploys
  mv ../$WEBNAM-$VERSION/webapp deploys/element-v$VERSION
  yarn install --frozen-lockfile \
               --ignore-engines \
               --no-fund \
               --update-checksums
  yarn run fetch --noverify --cfgdir ""
  CRATE_CC_NO_DEFAULTS=1 \
    yarn run build:native
  yarn run build --publish never

  install -d $PKG/$_PREFIX/{bin,lib$LIBDIRSUFFIX,share/applications}
  cp -aR dist/linux-unpacked $PKG/$_PREFIX/lib$LIBDIRSUFFIX/$PRGNAM
  install -Dm644 $CWD/element-desktop.desktop $PKG/$_PREFIX/share/applications/io.element.Element.desktop
  sed -i "s|@PREFIX|$_PREFIX|" $PKG/$_PREFIX/share/applications/io.element.Element.desktop
  ln -s $_PREFIX/lib$LIBDIRSUFFIX/element-desktop/element-desktop $PKG/$_PREFIX/bin/
  for geometry in 16x16 24x24 32x32 48x48 64x64 96x96 128x128 256x256 512x512; do
    install -d $PKG/$_PREFIX/share/icons/hicolor/$geometry/apps
    magick build/icon.png -resize $geometry $PKG/$_PREFIX/share/icons/hicolor/$geometry/apps/$PRGNAM.png
  done
  install -Dm644 -t $PKG/$_PREFIX/doc/$PRGNAM-$VERSION CHANGELOG.md CONTRIBUTING.md README.md LICENSE-* docs/*
}
