# Maintainer: Vladislav 'fsLeg' Borisov <fsleg at t-rg dot ws>

PRGNAM="tpm2-tss"
VERSION="4.2.0"
BUILD="${BUILD:-1}"
DESCRIPTION="OSS implementation of the TCG TPM2 Software Stack (TSS2)"
HOMEPAGE="https://tpm2-software.github.io/"
DOWNLOAD="https://github.com/tpm2-software/tpm2-tss/releases/download/${VERSION}/${PRGNAM}-${VERSION}.tar.gz"
SHA256SUM="b53f0c5c8c4ce17f05701a410ca9688f725ca380c9bc4640eacd0eadb1fea124"

unpack () {
  check_uid tss 374
  check_gid tss 374
  $UNTAR $CWD/$PRGNAM-$VERSION.tar.gz
}

build () {
  PATH=$PATH:/usr/sbin \
  ./configure \
    --prefix=$_PREFIX \
    --libdir=$_PREFIX/lib${LIBDIRSUFFIX} \
    --sysconfdir=$SYSCONFDIR \
    --localstatedir=$LOCALSTATEDIR \
    --mandir=$_PREFIX/man \
    --docdir=$_PREFIX/doc/$PRGNAM-$VERSION \
    --disable-static \
    --build=$ARCH-slackware-linux \
    --with-udevrulesdir=$SYSCONFDIR/udev/rules.d \
    --with-udevrulesprefix="60-" \
    --with-sysusersdir=/dev/null \
    --with-tmpfilesdir=/dev/null
  make

  make install DESTDIR=$PKG
  install -Dm644 -t $PKG/$_PREFIX/doc/$PRGNAM-$VERSION \
    CHANGELOG.md CONTRIBUTING.md LICENSE MAINTAINERS.md README.md
}
