# Maintainer: Vladislav 'fsLeg' Borisov <fsleg at t-rg dot ws>

PRGNAM="Botan"
VERSION="3.13.0"
BUILD="${BUILD:-1}"
DESCRIPTION="C++ crypto library"
HOMEPAGE="https://botan.randombit.net/"
DOWNLOAD="https://botan.randombit.net/releases/${PRGNAM%3}-${VERSION}.tar.xz"
SHA256SUM="12f5a8358890bbee82edfe9d2e7769b0a610b6dd0e0698aea13d20a675d84620"

unpack () {
  $UNTAR $CWD/$PRGNAM-$VERSION.tar.xz
}

build () {
  python3 configure.py \
    --prefix=$_PREFIX \
    --docdir=doc \
    --libdir=lib$LIBDIRSUFFIX \
    --mandir=$_PREFIX/man \
    --disable-static \
    --with-rst2man \
    --without-sphinx \
    $([[ "${DOCS@L}" == "yes" ]] && echo --with-doxygen) \
    --with-bzip2 \
    --with-zlib \
    --with-lzma \
    --with-boost \
    --with-sqlite3 \
    --with-commoncrypto
  make

  make install DESTDIR=$PKG
  mv $PKG/$_PREFIX/doc/${PRGNAM@L}-$VERSION $PKG/$_PREFIX/doc/$PRGNAM-$VERSION
  install -m644 -t $PKG/$_PREFIX/doc/$PRGNAM-$VERSION license.txt readme.rst
}
