# Maintainer: Vladislav 'fsLeg' Borisov <fsleg at t-rg dot ws>

PRGNAM="Botan"
VERSION="3.12.0"
BUILD="${BUILD:-1}"
DESCRIPTION="C++ crypto library"
HOMEPAGE="https://botan.randombit.net/"
DOWNLOAD="https://botan.randombit.net/releases/${PRGNAM%3}-${VERSION}.tar.xz"
SHA256SUM="5370f98dc15f8c222ee1ce52cd61c8756a53be0dc57cc4c1b0714d5a09ad74fb"

unpack () {
  tar xvf $CWD/$PRGNAM-$VERSION.tar.xz
}

build () {
  python3 configure.py \
    --prefix=$_PREFIX \
    --docdir=doc \
    --libdir=lib$LIBDIRSUFFIX \
    --mandir=$_PREFIX/man \
    --disable-static \
    --with-rst2man \
    --with-bzip2 \
    --with-zlib \
    --with-lzma \
    --with-boost \
    --with-sqlite3 \
    --with-commoncrypto
  make

  make install DESTDIR=$PKG
  mv $PKG/$_PREFIX/doc/${PRGNAM@L}-$VERSION $PKG/$_PREFIX/doc/$PRGNAM-$VERSION
  install -m644 -t $PKG/$_PREFIX/doc/$PRGNAM-$VERSION license.txt readme.rst
}
