# Maintainer: Vladislav 'fsLeg' Borisov <fsleg at t-rg dot ws>

PRGNAM="dumptorrent"
VERSION="1.7.0"
BUILD="${BUILD:-1}"
DESCRIPTION="get torrent metadata"
HOMEPAGE="https://github.com/tomcdj71/dumptorrent"
DOWNLOAD="https://github.com/tomcdj71/dumptorrent/archive/v${VERSION}/${PRGNAM}-${VERSION}.tar.gz"
SHA256SUM="0550782467b7e30c1b342196605b1d1476809c8508333faab1dc5ba46a933362"

unpack () {
  $UNTAR $CWD/$PRGNAM-$VERSION.tar.gz
}

build () {
  mkdir build
  cmake -B build/ \
    -DCMAKE_C_FLAGS="$SLKCFLAGS" \
    -DCMAKE_CXX_FLAGS="$SLKCFLAGS" \
    -DCMAKE_BUILD_TYPE="Release"
  cmake --build build/

  install -Dm755 -t $PKG/$_PREFIX/bin build/{dumptorrent,scrapec}
  install -Dm644 -t $PKG/$_PREFIX/doc/$PRGNAM-$VERSION README.md
}
