# Maintainer: Vladislav 'fsLeg' Borisov <fsleg at t-rg dot ws>

PRGNAM="qownnotes"
VERSION="26.2.4"
BUILD="${BUILD:-1}"
DESCRIPTION="notepad with markdown support and Nextcloud integration"
HOMEPAGE="https://www.qownnotes.org/"
DOWNLOAD="https://github.com/pbek/QOwnNotes/releases/download/v${VERSION}/${PRGNAM}-${VERSION}.tar.xz"
SHA256SUM="ca66be2897d9a9328ba5fc29cfc8fdfb06f093d0ae88eede30789454e908a906"
OPTIONAL="Botan3 libgit2 qt6"

unpack () {
  tar xvf $CWD/$PRGNAM-$VERSION.tar.xz

  # Set the release string to disable the update check
  echo '#define RELEASE "SlackBuild"' > release.h
}

build () {
  if [ "${QT6:-no}" != "no" ]; then
    USE_QT6="-DQON_QT6_BUILD=ON"
  fi

  if [ "${LIBGIT2:-no}" != "no" ]; then
    USE_LIBGIT2="-DBUILD_WITH_LIBGIT2=ON"
  fi

  if [ "${BOTAN:-no}" != "no" ]; then
    USE_SYSTEM_BOTAN="-DBUILD_WITH_SYSTEM_BOTAN=ON"
  fi

  mkdir build
  cmake \
    -DCMAKE_INSTALL_PREFIX=$_PREFIX \
    -DBUILD_WITH_ASPELL=ON \
    $USE_QT6 \
    $USE_LIBGIT2 \
    $USE_SYSTEM_BOTAN \
    -DCMAKE_BUILD_TYPE=Release \
    -B build
  cmake --build build

  DESTDIR=$PKG cmake --install build
  install -Dm644 -t $PKG/$_PREFIX/doc/$PRGNAM-$VERSION CHANGELOG.md LICENSE README.md shortcuts.md
}
