# Maintainer: Vladislav 'fsLeg' Borisov <fsleg at t-rg dot ws>

PRGNAM="ocserv"
VERSION="1.4.0"
BUILD="${BUILD:-1}"
DESCRIPTION="OpenConnect SSL VPN server"
HOMEPAGE="https://ocserv.openconnect-vpn.net"
DOWNLOAD="https://www.infradead.org/ocserv/download/${PRGNAM}-${VERSION}.tar.xz"
SHA256SUM="10d97d4aaec4e6b376e9c56d30720dec5384d813e69bb759e86b20c08115b15a"
REQUIRES="llhttp libev protobuf-c"
BUILD_REQUIRES="ipcalc-ng rubygem-ronn"

unpack () {
  check_uid ocserv 382
  check_gid ocserv 382
  tar xvf $CWD/$PRGNAM-$VERSION.tar.xz
}

build () {
  ./configure \
    --prefix=$_PREFIX \
    --libdir=$_PREFIX/lib${LIBDIRSUFFIX} \
    --sysconfdir=$SYSCONFDIR \
    --localstatedir=$LOCALSTATEDIR \
    --mandir=$_PREFIX/man \
    --docdir=$_PREFIX/doc/$PRGNAM-$VERSION \
    --disable-static \
    --build=$ARCH-slackware-linux
  make

  make install DESTDIR=$PKG
  install -Dm644 -t $PKG/$_PREFIX/doc/$PRGNAM-$VERSION \
    AUTHORS CONTRIBUTING* ChangeLog NEWS README* doc/README* doc/sample.* doc/scripts/*
  install -d $PKG/$SYSCONFDIR/{rc.d,ocserv}
  cat $CWD/rc.ocserv > $PKG/$SYSCONFDIR/rc.d/rc.ocserv.new
  cat $CWD/ocserv.conf > $PKG/$SYSCONFDIR/ocserv/ocserv.conf.new
  sed -i "s|@PREFIX@|$_PREFIX|g
          s|@SYSCONFDIR@|$LOCALSTATEDIR|g
          s|@LOCALSTATEDIR@|$LOCALSTATEDIR|g" \
          $PKG/$SYSCONFDIR/rc.d/rc.ocserv.new $PKG/$SYSCONFDIR/ocserv/ocserv.conf.new
}
