# Maintainer: Vladislav 'fsLeg' Borisov <fsleg at t-rg dot ws>

PRGNAM="shadowsocks-rust"
VERSION="1.25.0"
BUILD="${BUILD:-1}"
DESCRIPTION="rust port of shadowsocks, a secure socks5 proxy"
HOMEPAGE="https://github.com/shadowsocks/shadowsocks-rust"
DOWNLOAD="https://github.com/shadowsocks/shadowsocks-rust/archive/v${VERSION}/${PRGNAM}-${VERSION}.tar.gz"
SHA256SUM="477a525e9b11d4c90ded6629552548d00a32675ec6f6f18ee45c98447e54b5f3"
BUILD_REQUIRES=(rust-opt)

unpack () {
  $UNTAR $CWD/$PRGNAM-$VERSION.tar.gz
}

build () {
  cargo build --locked --release

  make install DESTDIR=$PKG TARGET=release PREFIX=$_PREFIX/bin
  install -d $PKG/$_PREFIX/doc/$PRGNAM-$VERSION
  cp -aR -t $PKG/$_PREFIX/doc/$PRGNAM-$VERSION \
            LICENSE README.md examples/
}
