# Maintainer: Vladislav 'fsLeg' Borisov <fsleg at t-rg dot ws>

PRGNAM="Botan3"
VERSION="3.11.1"
BUILD="${BUILD:-1}"
DESCRIPTION="C++ crypto library"
HOMEPAGE="https://botan.randombit.net/"
DOWNLOAD="https://botan.randombit.net/releases/${PRGNAM%3}-${VERSION}.tar.xz"
SHA256SUM="c1cd7152519f4188591fa4f6ddeb116bc1004491f5f3c58aa99b00582eb8a137"

unpack () {
  tar xvf $CWD/${PRGNAM%3}-$VERSION.tar.xz
  mv ${PRGNAM%3}-$VERSION $PRGNAM-$VERSION
}

build () {
  python3 configure.py \
    --prefix=$_PREFIX \
    --docdir=doc \
    --libdir=lib$LIBDIRSUFFIX \
    --mandir=$_PREFIX/man \
    --disable-static \
    --with-rst2man \
    --with-bzip2 \
    --with-zlib \
    --with-lzma \
    --with-boost \
    --with-sqlite3 \
    --with-commoncrypto \
    --program-suffix=3
  make

  make install DESTDIR=$PKG
  mv $PKG/$_PREFIX/man/man1/botan.1 $PKG/$_PREFIX/man/man1/botan3.1
  mv $PKG/$_PREFIX/doc/$(echo $PRGNAM | sed 's/^B/\L&/;s/3$//')-$VERSION $PKG/$_PREFIX/doc/$PRGNAM-$VERSION
  install -m644 -t $PKG/$_PREFIX/doc/$PRGNAM-$VERSION license.txt readme.rst
}
