# Maintainer: Vladislav 'fsLeg' Borisov <fsleg at t-rg dot ws>

PRGNAM="nodejs"
VERSION="22.23.2"
BUILD="${BUILD:-1}"
DESCRIPTION="JavaScript runtime"
HOMEPAGE="https://nodejs.org/"
DOWNLOAD="https://nodejs.org/dist/v${VERSION}/${PRGNAM%js}-v${VERSION}.tar.gz"
SHA256SUM="cdaed46fcd8923a55974b7bbc7caaadeaaf7aed60cc137e59837b72f575ef641"
CONFLICTS="nodejs18 nodejs22 nodejs24-bin"

unpack () {
  $UNTAR $CWD/${PRGNAM%js}-v$VERSION.tar.gz
  mv ${PRGNAM%js}-v$VERSION $PRGNAM-$VERSION

  # fix man page path
  sed -i 's|share/||' $PRGNAM-$VERSION/tools/install.py

  # fix libdir for 64-bit
  # https://github.com/iojs/io.js/issues/504
  sed -i "s|lib/|lib${LIBDIRSUFFIX}/|g" $PRGNAM-$VERSION/tools/install.py
  sed -i "s/'lib'/'lib${LIBDIRSUFFIX}'/" \
    $PRGNAM-$VERSION/lib/module.js \
    $PRGNAM-$VERSION/lib/internal/modules/cjs/loader.js \
    $PRGNAM-$VERSION/deps/npm/lib/npm.js

  # include the correct header
  sed -i "s|math.h|cmath|" $PRGNAM-$VERSION/src/node_crypto.cc

  # a workaround for a GCC 11.2 bug that prevents NodeJS 22 from building
  patch -p1 -d $PRGNAM-$VERSION < $CWD/nodejs22_gcc11.2_bug.patch
}

build () {
  ./configure \
    --prefix=$_PREFIX \
    --shared-openssl \
    --shared-zlib \
    --experimental-http-parser \
    --shared-nghttp2 \
    --shared-brotli \
    --ninja \
    --dest-cpu=$PLATFORM
  make CFLAGS="$SLKCFLAGS" CXXFLAGS="$SLKCFLAGS" LDFLAGS="-Wl,--copy-dt-needed-entries"

  make install DESTDIR=$PKG
  install -d $PKG/$_PREFIX/share/bash-completion/completions
  ln -sf $_PREFIX/lib$LIBDIRSUFFIX/node_modules/npm/lib/utils/completion.sh \
         $PKG/$_PREFIX/share/bash-completion/completions/npm
  compress_files $PKG/$_PREFIX/lib$LIBDIRSUFFIX/node_modules/npm/man
  install -Dm644 -t $PKG/$_PREFIX/doc/$PRGNAM-$VERSION LICENSE *.md
  mv $PKG/$_PREFIX/doc/node/* $PKG/$_PREFIX/doc/$PRGNAM-$VERSION/
  rmdir $PKG/$_PREFIX/doc/node
}
