# Maintainer: Vladislav 'fsLeg' Borisov <fsleg at t-rg dot ws>

PRGNAM="python3-keyring"
TARNAM="${PRGNAM#python3-}"
VERSION="25.7.0"
BUILD="${BUILD:-1}"
DESCRIPTION="Python keyring library"
HOMEPAGE="https://github.com/jaraco/keyring"
DOWNLOAD="https://files.pythonhosted.org/packages/source/k/${TARNAM}/${TARNAM}-${VERSION}.tar.gz"
SHA256SUM="fe01bd85eb3f8fb3dd0405defdeac9a5b4f6f0439edbb3149577f244a2e8245b"
REQUIRES="python-importlib_metadata python3-jaraco.classes python3-jaraco.context python3-jaraco.functools python3-secretstorage"
OPTIONAL="python3-shtab"

unpack () {
  tar xvf $CWD/$TARNAM-$VERSION.tar.gz
  mv $TARNAM-$VERSION $PRGNAM-$VERSION
  # drop useless coherent.licensed dependency
  sed -i '/coherent.licensed/d' $PRGNAM-$VERSION/pyproject.toml
}

build () {
  export PYTHONPATH=/opt/python$PYVER/site-packages
  python3 -m build --wheel --no-isolation

  python3 -m installer --destdir "$PKG" dist/*.whl
  # Add python3-keyring shell completions (requires python3-shtab)
  if $(python3 -c 'import importlib; exit(not importlib.util.find_spec("shtab"))'); then
    python3 -m venv --system-site-packages completion-env
    completion-env/bin/python -m installer dist/*.whl
    install -d $PKG/$_PREFIX/share/bash-completion/completions \
               $PKG/$_PREFIX/share/zsh/site-functions \
               $PKG/$SYSCONFDIR/profile.d
    completion-env/bin/keyring --print-completion bash > $PKG/$_PREFIX/share/bash-completion/completions/keyring
    completion-env/bin/keyring --print-completion zsh > $PKG/$_PREFIX/share/zsh/site-functions/_keyring
    completion-env/bin/keyring --print-completion tcsh > $PKG/$SYSCONFDIR/profile.d/keyring.csh
  fi
  install -Dm644 -t $PKG/$_PREFIX/doc/$PRGNAM-$VERSION LICENSE README.rst NEWS.rst SECURITY.md
}
