# Maintainer: Vladislav 'fsLeg' Borisov <fsleg at t-rg dot ws>

PRGNAM="llama.cpp"
VERSION="b10431"
BUILD="${BUILD:-1}"
DESCRIPTION="LLM inference in C/C++"
HOMEPAGE="https://llama-cpp.com/"
DOWNLOAD="https://github.com/ggml-org/llama.cpp/archive/${VERSION}/${PRGNAM}-${VERSION}.tar.gz"
SHA256SUM="9fa12ee5c681aef3cce914beafdc976635a68083342af23ca075b67db464b7b8"
OPTIONAL=(cudatoolkit_13 "nodejs|nodejs22|nodejs24-bin" OpenBLAS openvino rocmtoolkit_7)

unpack () {
  $UNTAR $CWD/$PRGNAM-$VERSION.tar.gz

  # Autodetect options
  if [[ ! -v CUDA ]] && command -v nvcc &> /dev/null; then
    CUDA="yes"
  fi

  if [[ ! -v HIP ]] && command -v hipconfig &> /dev/null; then
    HIP="yes"
  fi

  if [[ ! -v OPENBLAS ]] && pkg-config --exists openblas; then
    OPENBLAS="yes"
  fi

  if [[ ! -v VULKAN ]] && pkg-config --atleast-version=1.4 vulkan; then
    VULKAN="yes"
  fi

  if [[ ! -v OPENVINO ]] && pkg-config --exists openvino; then
    OPENVINO="yes"
  fi

  if [[ ! -v WEBUI ]] && command -v node &> /dev/null; then
    WEBUI="yes"
  fi

  # Set the options
  if [[ "$CUDA" == "yes" ]]; then
    USE_CUDA="-DGGML_CUDA=ON"
    REQUIRES+=(cudatoolkit_13)
  fi

  if [[ "$HIP" == "yes" ]]; then
    USE_HIP="-DGGML_HIP=ON"
    REQUIRES+=(rocmtoolkit_7)
  fi

  if [[ "$OPENBLAS" == "yes" ]]; then
    USE_OPENBLAS="-DGGML_BLAS=ON -DGGML_BLAS_VENDOR=OpenBLAS"
    [[ "$SLACKVER" != "current" ]] && REQUIRES+=(OpenBLAS)
  fi

  if [[ "$VULKAN" == "yes" ]]; then
    USE_VULKAN="-DGGML_VULKAN=ON"
    REQUIRES+=("vulkan-sdk >= 1.4")
  fi

  if [[ "$OPENVINO" == "yes" ]]; then
    USE_OPENVINO="-DGGML_OPENVINO=ON"
    REQUIRES+=(openvino)
  fi

  if [[ "$WEBUI" != "yes" ]]; then
    USE_WEBUI="-DLLAMA_BUILD_UI=OFF -DLLAMA_USE_PREBUILT_UI=OFF"
  fi
}

build () {
  cmake -B build \
        -DCMAKE_C_FLAGS="$SLKCFLAGS" \
        -DCMAKE_CXX_FLAGS="$SLKCFLAGS" \
        -DCMAKE_INSTALL_PREFIX="$_PREFIX" \
        $USE_CUDA \
        $USE_HIP \
        $USE_OPENBLAS \
        $USE_VULKAN \
        $USE_OPENVINO \
        $USE_WEBUI \
        -DLLAMA_BUILD_TESTS=OFF \
        -DGGML_BUILD_EXAMPLES=OFF \
        -DGGML_BUILD_TESTS=OFF \
        -DGGML_LTO=ON \
        -DBUILD_SHARED_LIBS=ON \
        -DLLAMA_BUILD_NUMBER="${VERSION#b}" \
        -Wno-dev
  cmake --build build \
        --config Release

  DESTDIR=$PKG \
  cmake --install build \
        --prefix $_PREFIX

  # workaround for not picking up own libraries
  patchelf --set-rpath "\$ORIGIN/../lib$LIBDIRSUFFIX" $PKG/$_PREFIX/bin/*

  install -d $PKG/$_PREFIX/doc/$PRGNAM-$VERSION
  cp -aR -t $PKG/$_PREFIX/doc/$PRGNAM-$VERSION \
    AGENTS.md AUTHORS CODEOWNERS CONTRIBUTING.md LICENSE README.md SECURITY.md docs/
}
