# Maintainer: Vladislav 'fsLeg' Borisov <fsleg at t-rg dot ws>

PRGNAM="llama.cpp"
VERSION="b9412"
BUILD="${BUILD:-1}"
DESCRIPTION="LLM inference in C/C++"
HOMEPAGE="https://llama-cpp.com/"
DOWNLOAD="https://github.com/ggml-org/llama.cpp/archive/${VERSION}/${PRGNAM}-${VERSION}.tar.gz"
SHA256SUM="97f34d7ebc0d4cbb3bc82777615852c0399c49b358b70cfcb6148e8071b86566"
OPTIONAL="cudatoolkit_13 nodejs|nodejs22|nodejs24-bin OpenBLAS rocmtoolkit_7"

unpack () {
  tar xvf $CWD/$PRGNAM-$VERSION.tar.gz

  if [[ ! -v CUDA ]] && command -v nvcc &> /dev/null; then
    CUDA="yes"
  fi

  if [[ ! -v HIP ]] && command -v hipconfig &> /dev/null; then
    HIP="yes"
  fi

  if [[ ! -v OPENBLAS ]] && pkg-config --exists openblas; then
    OPENBLAS="yes"
  fi

  if [[ ! -v VULKAN && $(pkg-config --modversion vulkan | cut -d. -f2) -ge 4 ]]; then
    VULKAN="yes"
  fi

  if [[ ! -v WEBUI ]] && command -v node &> /dev/null; then
    WEBUI="yes"
  fi
}

build () {
  cmake -B build \
        -DCMAKE_C_FLAGS="$SLKCFLAGS" \
        -DCMAKE_CXX_FLAGS="$SLKCFLAGS" \
        -DCMAKE_INSTALL_PREFIX="$_PREFIX" \
        $([[ "$CUDA" == "yes" ]] && echo "-DGGML_CUDA=ON") \
        $([[ "$HIP" == "yes" ]] && echo "-DGGML_HIP=ON") \
        $([[ "$OPENBLAS" == "yes" ]] && echo "-DGGML_BLAS=ON -DGGML_BLAS_VENDOR=OpenBLAS") \
        $([[ "$VULKAN" == "yes" ]] && echo "-DGGML_VULKAN=ON") \
        $([[ "$WEBUI" != "yes" ]] && echo "-DLLAMA_BUILD_UI=OFF -DLLAMA_USE_PREBUILT_UI=OFF") \
        -DLLAMA_BUILD_TESTS=OFF \
        -DGGML_BUILD_EXAMPLES=OFF \
        -DGGML_BUILD_TESTS=OFF \
        -DGGML_LTO=ON \
        -DBUILD_SHARED_LIBS=ON \
        -DLLAMA_BUILD_NUMBER="${VERSION#b}" \
        -Wno-dev
  cmake --build build \
        --config Release

  DESTDIR=$PKG \
  cmake --install build \
        --prefix $_PREFIX
  install -d $PKG/$_PREFIX/doc/$PRGNAM-$VERSION
  cp -aR -t $PKG/$_PREFIX/doc/$PRGNAM-$VERSION \
    AGENTS.md AUTHORS CODEOWNERS CONTRIBUTING.md LICENSE README.md SECURITY.md docs/
}
