# Maintainer: Vladislav 'fsLeg' Borisov <fsleg at t-rg dot ws>

PRGNAM="ollama"
VERSION="0.33.0"
BUILD="${BUILD:-1}"
DESCRIPTION="Download and run large language models locally"
HOMEPAGE="https://github.com/ollama/ollama"
DOWNLOAD="https://github.com/${PRGNAM}/${PRGNAM}/archive/v${VERSION}/${PRGNAM}-${VERSION}.tar.gz"
SHA256SUM="f2e727aee40dde9d646c221531044de1338ec51fbd958006258e5ed00087ebf3"
BUILD_REQUIRES=(cmake-opt google-go-lang)
OPTIONAL=(cudatoolkit_13 rocmtoolkit_7)

unpack () {
  check_gid ollama 393
  check_uid ollama 393
  $UNTAR $CWD/$PRGNAM-$VERSION.tar.gz

  if [[ ! -v CUDA ]] && command -v nvcc &> /dev/null; then
    CUDA="ON"
  fi

  if [[ ! -v ROCM ]] && command -v hipconfig &> /dev/null; then
    ROCM="ON"
  fi

  if [[ ! -v VULKAN ]] && pkg-config --atleast-version=1.4 vulkan; then
    VULKAN="ON"
  fi

  # At the moment MLX only supports MacOS despite being available for
  # other platforms. It's to the point that it's hardcoded to not work
  # on a non-MacOS.
  # https://github.com/ollama/ollama/issues/16265#issuecomment-4520099249
  # https://github.com/ollama/ollama/issues/16056#issuecomment-4412131363
  MLX="OFF"
  if [[ ! -v MLX ]] && pkg-config --exists openblas \
                    && pkg-config --exists cudnn \
                    && pkg-config --exists nccl; then
    MLX="ON"
    export CUDNN_INCLUDE_PATH="/usr/include/cudnn"
    export CUDNN_LIBRARY_PATH="/usr/lib64/cudnn"
  fi

  [[ "$CUDA"   == "ON" ]] && BACKENDS+="cuda_v13;"  && REQUIRES+=(cudatoolkit_13)
  [[ "$ROCM"   == "ON" ]] && BACKENDS+="rocm_v7_2;" && REQUIRES+=(rocmtoolkit_7)
  [[ "$VULKAN" == "ON" ]] && BACKENDS+="vulkan;"    && REQUIRES+=("vulkan-sdk >= 1.4")
  [[ "$MLX"    == "ON" ]]                           && REQUIRES+=(cudnn nccl OpenBLAS)

  [[ -v LLAMACPP ]] && echo "$LLAMACPP" > $PRGNAM-$VERSION/LLAMA_CPP_VERSION

  # don't copy system libraries
  # https://gitlab.archlinux.org/archlinux/packaging/packages/ollama/-/blob/main/PKGBUILD?ref_type=heads
  sed -i 's/PRE_INCLUDE_REGEXES.*/PRE_INCLUDE_REGEXES = ""/g' \
    $PRGNAM-$VERSION/llama/server/CMakeLists.txt \
    $PRGNAM-$VERSION/cmake/mlx/CMakeLists.txt

  # fix hardcoded path
  # https://data.gpo.zugaina.org/guru/sci-ml/ollama/ollama-0.21.2.ebuild
  # grep -Rl -e 'lib/ollama' -e '"..", "lib"'  --include '*.go'
  sed -i "s|\"..\", \"lib\"|\"..\", \"lib$LIBDIRSUFFIX\"|g
          s|\"lib/ollama\"|\"lib$LIBDIRSUFFIX/ollama\"|g" \
      $PRGNAM-$VERSION/llm/llama_binary.go \
      $PRGNAM-$VERSION/ml/path.go
  sed -i '/"CUDA_PATH"/d; /"CUDA_HOME"/d' \
      $PRGNAM-$VERSION/x/mlxrunner/client.go

  # add "PARAMETER think" for Modelfile, PR14108
  patch -p1 -d $PRGNAM-$VERSION -i $CWD/14108.patch
}

build () {
  cmake -B build \
        -DOLLAMA_LIB_DIR="lib$LIBDIRSUFFIX/$PRGNAM" \
        -DOLLAMA_VERSION="$VERSION" \
        $([[ -n "$BACKENDS" ]] && echo "-DOLLAMA_LLAMA_BACKENDS=${BACKENDS%;}") \
        $([[ "$CUDA" == "ON" ]] && echo "-DCMAKE_CUDA_ARCHITECTURES=native") \
        $([[ "$MLX" == "ON" ]] && echo "-DOLLAMA_MLX_BACKENDS=cuda_v13" )
  cmake --build build

  DESTDIR=$PKG \
    cmake --install build \
          --prefix "$_PREFIX"

  ODIR="$PKG/$_PREFIX/lib$LIBDIRSUFFIX/$PRGNAM"
  # workarounds for not finding libraries
  for LIB in $ODIR/{libggml-cpu-*.so,llama-*}; do
    if patchelf --print-rpath $LIB | grep -q $TMP; then
      patchelf --set-rpath '$ORIGIN' $LIB
    fi
  done
  for BACKEND in cuda_v13 rocm_v7_2 vulkan; do
    if [[ -d "$ODIR/$BACKEND" ]]; then
      mv $ODIR/$BACKEND/*.so $ODIR/
      rmdir $ODIR/$BACKEND
    fi
  done

  # Don't bundle libraries and headers for MLX engine
  if [[ "$MLX" == "ON" ]]; then
    rm -f $ODIR/mlx_cuda_v13/lib{cudart,cublas,cublasLt,nvrtc,nvrtc-builtins,cufft,cudnn}.so*
    rm -rf $ODIR/mlx_cuda_v13/include/cccl
    find $ODIR/mlx_cuda_v13/include -mindepth 1 -maxdepth 1 ! -name "libmlx*" -type f \
      -exec rm -f {} \+
    find $PKG/$_PREFIX/lib$LIBDIRSUFFIX -mindepth 1 -maxdepth 1 ! -name ollama \
      -exec rm -rf {} \+
  fi
  
  install -Dm755 -t $PKG/$_PREFIX/bin $PRGNAM
  install -Dm755 $CWD/rc.$PRGNAM $PKG/$SYSCONFDIR/rc.d/rc.$PRGNAM.new
  install -Dm644 $CWD/$PRGNAM.default $PKG/$SYSCONFDIR/default/$PRGNAM.new
  install -Dm644 $CWD/$PRGNAM.logrotate $PKG/$SYSCONFDIR/logrotate.d/$PRGNAM.new
  sed -i "s|@PREFIX@|$_PREFIX|g
          s|@SYSCONFDIR@|$SYSCONFDIR|g
          s|@LOCALSTATEDIR@|$LOCALSTATEDIR|g" \
      $PKG/$SYSCONFDIR/rc.d/rc.$PRGNAM.new \
      $PKG/$SYSCONFDIR/default/$PRGNAM.new \
      $PKG/$SYSCONFDIR/logrotate.d/$PRGNAM.new

  install -d $PKG/$_PREFIX/doc/$PRGNAM-$VERSION
  cp -aR -t $PKG/$_PREFIX/doc/$PRGNAM-$VERSION \
    CONTRIBUTING.md LICENSE README.md SECURITY.md docs/
  install -d $PKG/install
  sed "s|@SYSCONFDIR@|${SYSCONFDIR#/}|g" \
       $CWD/doinst.sh > $PKG/install/doinst.sh
}
