# Maintainer: Vladislav 'fsLeg' Borisov <fsleg at t-rg dot ws>

PRGNAM="ollama"
VERSION="0.24.0"
BUILD="${BUILD:-1}"
DESCRIPTION="Download and run large language models locally"
HOMEPAGE="https://github.com/ollama/ollama"
DOWNLOAD="https://github.com/${PRGNAM}/${PRGNAM}/archive/v${VERSION}/${PRGNAM}-${VERSION}.tar.gz"
SHA256SUM="a97e4a545cb08ed0343f97dc964be49f707b8404f1c2e29ec1338ec96b556eb2"
BUILD_REQUIRES="cmake-opt google-go-lang"
OPTIONAL="cudatoolkit_13 rocmtoolkit_7"

unpack () {
  check_gid ollama 393
  check_uid ollama 393
  tar xfv $CWD/$PRGNAM-$VERSION.tar.gz

  if ! pkg-config --atleast-version=1.4 vulkan; then
    # disabling ggml-vulkan until we have vulkan-sdk >= 1.4
    sed -i '/find_package(Vulkan)/d' $PRGNAM-$VERSION/CMakeLists.txt
  fi

  # add "PARAMETER think" for Modelfile, PR14108
  patch -p1 -d $PRGNAM-$VERSION -i $CWD/14108.patch

  # https://build.opensuse.org/projects/openSUSE:Factory/packages/ollama/files/ollama.spec?expand=1
  sed -i "s|\(\${CMAKE_BINARY_DIR}\)/lib/ollama|\1/lib$LIBDIRSUFFIX/ollama|g
          s|\(\${CMAKE_INSTALL_PREFIX}\)/lib/ollama|\1/lib$LIBDIRSUFFIX/ollama|g" \
      $PRGNAM-$VERSION/CMakeLists.txt

  # https://data.gpo.zugaina.org/guru/sci-ml/ollama/ollama-0.21.2.ebuild
  # grep -Rl -e 'lib/ollama' -e '"..", "lib"'  --include '*.go'
  sed -i "s|\"..\", \"lib\"|\"..\", \"lib$LIBDIRSUFFIX\"|g
          s|\"lib/ollama\"|\"lib$LIBDIRSUFFIX/ollama\"|g" \
      $PRGNAM-$VERSION/ml/backend/ggml/ggml/src/ggml.go \
      $PRGNAM-$VERSION/ml/path.go
}

build () {
  cmake -B build \
        -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
        -DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
        -DCMAKE_INSTALL_PREFIX="$_PREFIX" \
        -DCMAKE_BUILD_TYPE="Release" \
        -DGGML_BACKEND_DL="yes" \
        -DGGML_BACKEND_DIR="$_PREFIX/lib$LIBDIRSUFFIX/$PRGNAM"
  cmake --build build

  go build -v \
           -buildmode=pie \
           -trimpath \
           -mod=readonly \
           -modcacherw \
           -ldflags "-linkmode external \
                     -X=github.com/ollama/ollama/version.Version=$VERSION \
                     -X=github.com/ollama/ollama/server.mode=release \
                     -extldflags '${LDFLAGS}'" \
           -o build

  DESTDIR=$PKG cmake --install build
  install -Dm755 -t $PKG/$_PREFIX/bin build/$PRGNAM
  install -Dm755 $CWD/rc.$PRGNAM $PKG/$SYSCONFDIR/rc.d/rc.$PRGNAM.new
  install -Dm644 $CWD/$PRGNAM.default $PKG/$SYSCONFDIR/default/$PRGNAM.new
  install -Dm644 $CWD/$PRGNAM.logrotate $PKG/$SYSCONFDIR/logrotate.d/$PRGNAM.new
  sed -i "s|@PREFIX@|$_PREFIX|g
          s|@SYSCONFDIR@|$SYSCONFDIR|g
          s|@LOCALSTATEDIR@|$LOCALSTATEDIR|g" \
      $PKG/$SYSCONFDIR/rc.d/rc.$PRGNAM.new \
      $PKG/$SYSCONFDIR/default/$PRGNAM.new \
      $PKG/$SYSCONFDIR/logrotate.d/$PRGNAM.new

  install -d $PKG/$_PREFIX/doc/$PRGNAM-$VERSION
  cp -aR -t $PKG/$_PREFIX/doc/$PRGNAM-$VERSION \
    CONTRIBUTING.md LICENSE README.md SECURITY.md docs/
  install -d $PKG/install
  sed "s|@SYSCONFDIR@|${SYSCONFDIR#/}|g" \
       $CWD/doinst.sh > $PKG/install/doinst.sh
}
