# Maintainer: Vladislav 'fsLeg' Borisov <fsleg at t-rg dot ws>

PRGNAM="amneziawg-go"
VERSION="3.0.1"
BUILD="${BUILD:-1}"
DESCRIPTION="AmneziaWG VPN protocol"
HOMEPAGE="https://github.com/amnezia-vpn/amneziawg-go"
DOWNLOAD="https://github.com/amnezia-vpn/amneziawg-go/archive/v${VERSION}/${PRGNAM}-${VERSION}.tar.gz"
SHA256SUM="dedf7e6025e9508572207dd6a14e67e851449dc7abee26ffd437d4b14206e75b"
BUILD_REQUIRES="google-go-lang"

unpack () {
  tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
}

build () {
  go build -v

  install -Dm755 -t $PKG/$_PREFIX/sbin amneziawg-go
  install -Dm644 -t $PKG/$_PREFIX/doc/$PRGNAM-$VERSION LICENSE README.md
}
