# Maintainer: Vladislav 'fsLeg' Borisov <fsleg at t-rg dot ws>

PRGNAM="ccid"
VERSION="1.8.3"
BUILD="${BUILD:-1}"
DESCRIPTION="PC/SC driver for USB CCID smart card readers"
HOMEPAGE="https://ccid.apdu.fr/"
DOWNLOAD="https://ccid.apdu.fr/files/${PRGNAM}-${VERSION}.tar.xz"
SHA256SUM="2f22877569154a75d54922db45c4e0cb3d290e72c60c574dc08966599cdcc5ac"
REQUIRES=(pcsc-lite)

unpack () {
  $UNTAR $CWD/$PRGNAM-$VERSION.tar.xz
}

build () {
  meson setup --prefix=$_PREFIX \
              --libdir=$_PREFIX/lib$LIBDIRSUFFIX \
              --sysconfdir=$SYSCONFDIR \
              -Dclass=true \
              -Dserial=true \
              -Dcomposite-as-multislot=true \
              -Dzlp=true \
              -Denable-extras=true \
              -Dstrip=true \
        build

  meson compile -C build
  meson install -C build --destdir=$PKG

  mkdir -p $PKG/$_PREFIX/doc/$PRGNAM-$VERSION
  cp -a AUTHORS COPYING README.md SCARD*.md \
    $PKG/$_PREFIX/doc/$PRGNAM-$VERSION
}
